/* AQcredix — department audit scope. GENERATED FILE, DO NOT EDIT BY HAND.
 *
 * Source: 5thEdChkList.pdf (NABH 5th Edition assessor checklist), transcribed in
 * build/scope-source.js and expanded by build/build-scope.js. Regenerate with:
 *
 *     node build/build-scope.js
 *
 * Scope is taken from the printed assessor checklist rather than from keyword matching,
 * because which elements an assessor checks in a given area is a published fact, not
 * something to infer from a regex. DEPT_DATA keywords stay where they are, driving the
 * department deep-dive pages.
 *
 * Every code below is verified to exist in nabh-data.js at build time.
 * Chapter aliases applied: HIC -> IPC, CQI -> PSQ.
 */
window.AUDIT_SCOPE = {
 "emergency": {
  "key": "emergency",
  "name": "Emergency Room",
  "group": "clinical",
  "pdfPage": 4,
  "inherits": null,
  "quickList": [
   "Policies on dead on arrival, transfer/discharge, non-availability of beds",
   "Access to emergency",
   "Quality assurance",
   "Ambulance communication",
   "Medication management",
   "CPR — assigned roles and responsibilities",
   "Equipment / furniture maintenance",
   "Crowd management",
   "Clinical pathways",
   "Dead on arrival",
   "Identified area for emergency care, defined beds",
   "Triage",
   "MLC",
   "Disaster management — plan tested twice a year",
   "BMW",
   "Infection control",
   "Case records — documentation",
   "Fire safety",
   "Medical gas",
   "Reassessment",
   "Discharge / transfer note — DTH patients or transfer to another organisation"
  ],
  "kpis": [
   "PSQ 3a(1) Time for initial assessment",
   "PSQ 3a(11) Return to Emergency within 72 hrs with similar presenting complaints",
   "PSQ 3b Hand hygiene compliance; compliance to medication prescription in capitals",
   "PSQ 3a(4) Medication error rate",
   "PSQ 4d(i) Number of variations in mock drills (disaster management)"
  ],
  "codes": [
   "AAC.1.c",
   "AAC.2.e",
   "AAC.3.a",
   "AAC.3.b",
   "AAC.3.c",
   "AAC.3.d",
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.g",
   "AAC.12.d",
   "AAC.13.d",
   "COP.1.e",
   "COP.2.a",
   "COP.2.b",
   "COP.2.c",
   "COP.2.d",
   "COP.2.e",
   "COP.2.f",
   "COP.2.g",
   "COP.2.h",
   "COP.2.i",
   "COP.3.a",
   "COP.4.a",
   "COP.4.b",
   "COP.4.c",
   "COP.4.d",
   "COP.5.a",
   "COP.5.b",
   "COP.5.c",
   "COP.6.a",
   "COP.6.b",
   "COP.6.e",
   "COP.6.f",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.9.b",
   "COP.9.e",
   "COP.13.a",
   "COP.13.b",
   "COP.13.c",
   "COP.13.d",
   "COP.13.e",
   "COP.13.f",
   "COP.13.g",
   "COP.13.h",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "PRE.8.b",
   "PRE.8.c",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.8.b",
   "IPC.8.e",
   "PSQ.3.a",
   "PSQ.3.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.3.e",
   "FMS.3.f",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f"
  ]
 },
 "ambulance": {
  "key": "ambulance",
  "name": "Ambulance",
  "group": "clinical",
  "pdfPage": 7,
  "inherits": null,
  "quickList": [
   "Access to ambulance services commensurate with scope",
   "Parking adequacy",
   "National ambulance code AIS-125",
   "Statutory requirements — RC, fitness, licence, insurance, PUC",
   "Trained personnel",
   "Checklist of ambulance drugs and equipment",
   "Cleaning after each transport",
   "Communication system",
   "MOU if outsourced"
  ],
  "kpis": [],
  "codes": [
   "COP.3.a",
   "COP.3.b",
   "COP.3.c",
   "COP.3.d",
   "COP.3.e",
   "COP.3.f",
   "COP.3.g",
   "ROM.5.e",
   "ROM.5.f"
  ]
 },
 "opd": {
  "key": "opd",
  "name": "Out Patient Department",
  "group": "clinical",
  "pdfPage": 7,
  "inherits": null,
  "quickList": [
   "Initial assessment — outpatients, daycare",
   "Priority access on clinical needs",
   "Follow-up date",
   "Patients' rights displayed — right to respect for values and belief",
   "Case records — documentation",
   "Complaint redressal, feedback",
   "Medical gas",
   "Vulnerable patients",
   "Infection control",
   "Display of scope in Obs/Paed",
   "Admission process",
   "Drug reconciliation in admissions",
   "Medication management",
   "CAPITAL letters — prescription",
   "Physician's sample drugs",
   "Fire safety",
   "BMW",
   "Equipment / furniture maintenance"
  ],
  "kpis": [
   "PSQ 3d(32) Compliance rate to medication prescription in capitals",
   "PSQ 3c(22) Waiting time for out-patient consultation"
  ],
  "codes": [
   "AAC.2.a",
   "AAC.2.b",
   "AAC.2.c",
   "AAC.2.d",
   "AAC.2.e",
   "AAC.3.b",
   "AAC.3.c",
   "AAC.3.d",
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.f",
   "AAC.4.g",
   "AAC.5.b",
   "COP.10.b",
   "COP.10.d",
   "COP.10.e",
   "COP.11.b",
   "COP.11.e",
   "COP.11.f",
   "COP.11.h",
   "COP.16.b",
   "COP.16.c",
   "COP.16.d",
   "MOM.3.c",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "PRE.1.a",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.2.l",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.b",
   "PRE.4.c",
   "PRE.5.f",
   "PRE.6.a",
   "PRE.6.b",
   "PRE.7.a",
   "PRE.7.b",
   "PRE.7.c",
   "PRE.8.b",
   "PRE.8.c",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.8.b",
   "IPC.8.e",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e"
  ]
 },
 "wards": {
  "key": "wards",
  "name": "Wards",
  "group": "clinical",
  "pdfPage": 10,
  "inherits": null,
  "quickList": [
   "Initial assessment & reassessment",
   "Care plan",
   "Nursing care according to current standard of practice",
   "CPR — assigned roles and responsibilities",
   "Documentation of hand-over",
   "Safe transfer of patients",
   "Pain management",
   "Nutritional assessment",
   "Blood transfusion",
   "Vulnerable patients",
   "Patients' rights displayed",
   "Patient feedback",
   "Medical gas",
   "Equipment / furniture maintenance",
   "Medication reconciliation",
   "Monitoring of patients after medication administration",
   "Appropriate and adequate equipment",
   "Admission process",
   "Planned discharges",
   "Discharge & discharge summary",
   "Early warning signs",
   "Case records — documentation",
   "Referrals",
   "Physician's sample drugs",
   "Medication orders",
   "Medication management",
   "Narcotics",
   "Restraint policy",
   "Hazmat",
   "Fire safety",
   "BMW",
   "Infection control",
   "Hand hygiene",
   "DVT",
   "Pressure ulcers",
   "Patient experience"
  ],
  "kpis": [
   "PSQ 3a(1) Time for initial assessment",
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(4) Percentage of medication charts with error prone abbreviations",
   "PSQ 3a(6) Percentage of patients developing ADRs",
   "PSQ 3a(8) Percentage of cases — prevent adverse events like wrong site, patient, surgery",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3a(9) Incidence of hospital associated pressure ulcers after admission",
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 3d(32) Compliance rate to medication prescription in capitals",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses",
   "PSQ 4c(24) Time taken for discharge"
  ],
  "codes": [
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.d",
   "AAC.4.e",
   "AAC.4.f",
   "AAC.4.g",
   "AAC.5.a",
   "AAC.5.c",
   "AAC.5.d",
   "AAC.5.e",
   "AAC.12.a",
   "AAC.12.b",
   "AAC.12.c",
   "AAC.12.d",
   "AAC.12.e",
   "AAC.12.f",
   "AAC.12.g",
   "AAC.13.a",
   "AAC.13.b",
   "AAC.13.c",
   "AAC.13.d",
   "AAC.13.e",
   "COP.1.a",
   "COP.1.d",
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.6.a",
   "COP.6.b",
   "COP.6.c",
   "COP.6.d",
   "COP.6.e",
   "COP.6.f",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.8.b",
   "COP.8.d",
   "COP.8.g",
   "COP.14.a",
   "COP.14.b",
   "COP.14.c",
   "COP.14.d",
   "COP.16.a",
   "COP.16.b",
   "COP.16.c",
   "COP.16.d",
   "COP.16.e",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.19.a",
   "COP.19.b",
   "COP.19.c",
   "COP.19.d",
   "COP.19.e",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.8.a",
   "MOM.8.b",
   "MOM.8.c",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "PRE.1.a",
   "PRE.1.b",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.b",
   "PRE.4.c",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.5.h",
   "PRE.7.b",
   "PRE.8.b",
   "PRE.8.c",
   "PRE.8.e",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.d",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.8.a",
   "IPC.8.b",
   "IPC.8.c",
   "IPC.8.d",
   "IPC.8.e",
   "FMS.1.a",
   "FMS.1.b",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.3.a",
   "FMS.3.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.a",
   "FMS.4.b",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f",
   "FMS.4.g",
   "FMS.4.h",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.4.b"
  ]
 },
 "paediatric": {
  "key": "paediatric",
  "name": "Paediatric Ward",
  "group": "clinical",
  "pdfPage": 14,
  "inherits": "wards",
  "quickList": [
   "Initial assessment & reassessment",
   "Care plan",
   "Nursing care according to current standard of practice",
   "CPR — assigned roles and responsibilities",
   "Documentation of hand-over",
   "Safe transfer of patients",
   "Pain management",
   "Nutritional assessment",
   "Blood transfusion",
   "Vulnerable patients",
   "Patients' rights displayed",
   "Patient feedback",
   "Medical gas",
   "Equipment / furniture maintenance",
   "Medication reconciliation",
   "Monitoring of patients after medication administration",
   "Appropriate and adequate equipment",
   "Admission process",
   "Planned discharges",
   "Discharge & discharge summary",
   "Early warning signs",
   "Case records — documentation",
   "Referrals",
   "Physician's sample drugs",
   "Medication orders",
   "Medication management",
   "Narcotics",
   "Restraint policy",
   "Hazmat",
   "Fire safety",
   "BMW",
   "Infection control",
   "Hand hygiene",
   "DVT",
   "Pressure ulcers",
   "Patient experience",
   "Provision for special care of children",
   "Prevention of child abduction",
   "Credentialing & privileging"
  ],
  "kpis": [
   "PSQ 3a(1) Time for initial assessment",
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(4) Percentage of medication charts with error prone abbreviations",
   "PSQ 3a(6) Percentage of patients developing ADRs",
   "PSQ 3a(8) Percentage of cases — prevent adverse events like wrong site, patient, surgery",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3a(9) Incidence of hospital associated pressure ulcers after admission",
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 3d(32) Compliance rate to medication prescription in capitals",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses",
   "PSQ 4c(24) Time taken for discharge"
  ],
  "codes": [
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.d",
   "AAC.4.e",
   "AAC.4.f",
   "AAC.4.g",
   "AAC.5.a",
   "AAC.5.c",
   "AAC.5.d",
   "AAC.5.e",
   "AAC.12.a",
   "AAC.12.b",
   "AAC.12.c",
   "AAC.12.d",
   "AAC.12.e",
   "AAC.12.f",
   "AAC.12.g",
   "AAC.13.a",
   "AAC.13.b",
   "AAC.13.c",
   "AAC.13.d",
   "AAC.13.e",
   "COP.1.a",
   "COP.1.d",
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.6.a",
   "COP.6.b",
   "COP.6.c",
   "COP.6.d",
   "COP.6.e",
   "COP.6.f",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.8.b",
   "COP.8.d",
   "COP.8.g",
   "COP.11.a",
   "COP.11.b",
   "COP.11.c",
   "COP.11.d",
   "COP.11.e",
   "COP.11.f",
   "COP.11.g",
   "COP.11.h",
   "COP.14.a",
   "COP.14.b",
   "COP.14.c",
   "COP.14.d",
   "COP.16.a",
   "COP.16.b",
   "COP.16.c",
   "COP.16.d",
   "COP.16.e",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.19.a",
   "COP.19.b",
   "COP.19.c",
   "COP.19.d",
   "COP.19.e",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.8.a",
   "MOM.8.b",
   "MOM.8.c",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "PRE.1.a",
   "PRE.1.b",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.b",
   "PRE.4.c",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.5.h",
   "PRE.7.b",
   "PRE.8.b",
   "PRE.8.c",
   "PRE.8.e",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.d",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.8.a",
   "IPC.8.b",
   "IPC.8.c",
   "IPC.8.d",
   "IPC.8.e",
   "FMS.1.a",
   "FMS.1.b",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.3.a",
   "FMS.3.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.a",
   "FMS.4.b",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f",
   "FMS.4.g",
   "FMS.4.h",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.4.b"
  ]
 },
 "obg": {
  "key": "obg",
  "name": "Obstetrics & Gynaecology and Labour Room",
  "group": "clinical",
  "pdfPage": 14,
  "inherits": "wards",
  "quickList": [
   "Initial assessment & reassessment",
   "Care plan",
   "Nursing care according to current standard of practice",
   "CPR — assigned roles and responsibilities",
   "Documentation of hand-over",
   "Safe transfer of patients",
   "Pain management",
   "Nutritional assessment",
   "Blood transfusion",
   "Vulnerable patients",
   "Patients' rights displayed",
   "Patient feedback",
   "Medical gas",
   "Equipment / furniture maintenance",
   "Medication reconciliation",
   "Monitoring of patients after medication administration",
   "Appropriate and adequate equipment",
   "Admission process",
   "Planned discharges",
   "Discharge & discharge summary",
   "Early warning signs",
   "Case records — documentation",
   "Referrals",
   "Physician's sample drugs",
   "Medication orders",
   "Medication management",
   "Narcotics",
   "Restraint policy",
   "Hazmat",
   "Fire safety",
   "BMW",
   "Infection control",
   "Hand hygiene",
   "DVT",
   "Pressure ulcers",
   "Patient experience",
   "High risk obstetrics",
   "MTP",
   "Pre, peri & post natal monitoring",
   "Credentialing & privileging"
  ],
  "kpis": [
   "PSQ 3a(1) Time for initial assessment",
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(4) Percentage of medication charts with error prone abbreviations",
   "PSQ 3a(6) Percentage of patients developing ADRs",
   "PSQ 3a(8) Percentage of cases — prevent adverse events like wrong site, patient, surgery",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3a(9) Incidence of hospital associated pressure ulcers after admission",
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 3d(32) Compliance rate to medication prescription in capitals",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses",
   "PSQ 4c(24) Time taken for discharge"
  ],
  "codes": [
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.d",
   "AAC.4.e",
   "AAC.4.f",
   "AAC.4.g",
   "AAC.5.a",
   "AAC.5.c",
   "AAC.5.d",
   "AAC.5.e",
   "AAC.12.a",
   "AAC.12.b",
   "AAC.12.c",
   "AAC.12.d",
   "AAC.12.e",
   "AAC.12.f",
   "AAC.12.g",
   "AAC.13.a",
   "AAC.13.b",
   "AAC.13.c",
   "AAC.13.d",
   "AAC.13.e",
   "COP.1.a",
   "COP.1.c",
   "COP.1.d",
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.6.a",
   "COP.6.b",
   "COP.6.c",
   "COP.6.d",
   "COP.6.e",
   "COP.6.f",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.8.b",
   "COP.8.d",
   "COP.8.g",
   "COP.10.a",
   "COP.10.b",
   "COP.10.c",
   "COP.10.d",
   "COP.10.e",
   "COP.10.f",
   "COP.10.g",
   "COP.14.a",
   "COP.14.b",
   "COP.14.c",
   "COP.14.d",
   "COP.16.a",
   "COP.16.b",
   "COP.16.c",
   "COP.16.d",
   "COP.16.e",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.19.a",
   "COP.19.b",
   "COP.19.c",
   "COP.19.d",
   "COP.19.e",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.8.a",
   "MOM.8.b",
   "MOM.8.c",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.9.e",
   "PRE.1.a",
   "PRE.1.b",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.b",
   "PRE.4.c",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.5.h",
   "PRE.7.b",
   "PRE.8.b",
   "PRE.8.c",
   "PRE.8.e",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.d",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.8.a",
   "IPC.8.b",
   "IPC.8.c",
   "IPC.8.d",
   "IPC.8.e",
   "ROM.2.b",
   "FMS.1.a",
   "FMS.1.b",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.3.a",
   "FMS.3.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.a",
   "FMS.4.b",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f",
   "FMS.4.g",
   "FMS.4.h",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.4.b"
  ]
 },
 "chemotherapy": {
  "key": "chemotherapy",
  "name": "Chemotherapy Unit",
  "group": "clinical",
  "pdfPage": 15,
  "inherits": "wards",
  "quickList": [
   "Initial assessment & reassessment",
   "Care plan",
   "Nursing care according to current standard of practice",
   "CPR — assigned roles and responsibilities",
   "Documentation of hand-over",
   "Safe transfer of patients",
   "Pain management",
   "Nutritional assessment",
   "Blood transfusion",
   "Vulnerable patients",
   "Patients' rights displayed",
   "Patient feedback",
   "Medical gas",
   "Equipment / furniture maintenance",
   "Medication reconciliation",
   "Monitoring of patients after medication administration",
   "Appropriate and adequate equipment",
   "Admission process",
   "Planned discharges",
   "Discharge & discharge summary",
   "Early warning signs",
   "Case records — documentation",
   "Referrals",
   "Physician's sample drugs",
   "Medication orders",
   "Medication management",
   "Narcotics",
   "Restraint policy",
   "Hazmat",
   "Fire safety",
   "BMW",
   "Infection control",
   "Hand hygiene",
   "DVT",
   "Pressure ulcers",
   "Patient experience",
   "Chemotherapy management",
   "Narcotics",
   "Disposal of chemo drugs",
   "Credentialing & privileging"
  ],
  "kpis": [
   "PSQ 3a(1) Time for initial assessment",
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(4) Percentage of medication charts with error prone abbreviations",
   "PSQ 3a(6) Percentage of patients developing ADRs",
   "PSQ 3a(8) Percentage of cases — prevent adverse events like wrong site, patient, surgery",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3a(9) Incidence of hospital associated pressure ulcers after admission",
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 3d(32) Compliance rate to medication prescription in capitals",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses",
   "PSQ 4c(24) Time taken for discharge"
  ],
  "codes": [
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.d",
   "AAC.4.e",
   "AAC.4.f",
   "AAC.4.g",
   "AAC.5.a",
   "AAC.5.c",
   "AAC.5.d",
   "AAC.5.e",
   "AAC.12.a",
   "AAC.12.b",
   "AAC.12.c",
   "AAC.12.d",
   "AAC.12.e",
   "AAC.12.f",
   "AAC.12.g",
   "AAC.13.a",
   "AAC.13.b",
   "AAC.13.c",
   "AAC.13.d",
   "AAC.13.e",
   "COP.1.a",
   "COP.1.d",
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.6.a",
   "COP.6.b",
   "COP.6.c",
   "COP.6.d",
   "COP.6.e",
   "COP.6.f",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.8.b",
   "COP.8.d",
   "COP.8.g",
   "COP.14.a",
   "COP.14.b",
   "COP.14.c",
   "COP.14.d",
   "COP.16.a",
   "COP.16.b",
   "COP.16.c",
   "COP.16.d",
   "COP.16.e",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.19.a",
   "COP.19.b",
   "COP.19.c",
   "COP.19.d",
   "COP.19.e",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.8.a",
   "MOM.8.b",
   "MOM.8.c",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.9.e",
   "PRE.1.a",
   "PRE.1.b",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.b",
   "PRE.4.c",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.5.h",
   "PRE.7.b",
   "PRE.8.b",
   "PRE.8.c",
   "PRE.8.e",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.d",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.8.a",
   "IPC.8.b",
   "IPC.8.c",
   "IPC.8.d",
   "IPC.8.e",
   "FMS.1.a",
   "FMS.1.b",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.3.a",
   "FMS.3.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.a",
   "FMS.4.b",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f",
   "FMS.4.g",
   "FMS.4.h",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.4.b"
  ]
 },
 "palliative": {
  "key": "palliative",
  "name": "Palliative Care",
  "group": "clinical",
  "pdfPage": 16,
  "inherits": null,
  "quickList": [
   "Pain management",
   "End of life care",
   "Narcotics",
   "Multi-professional approach"
  ],
  "kpis": [],
  "codes": [
   "COP.16.a",
   "COP.17.c",
   "COP.17.d",
   "COP.20.a",
   "COP.20.b",
   "COP.20.c",
   "COP.20.d",
   "COP.20.e",
   "MOM.5.a",
   "MOM.5.b",
   "MOM.5.c",
   "MOM.5.d",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.7.e",
   "MOM.7.f",
   "MOM.7.g",
   "MOM.7.h",
   "MOM.7.i",
   "MOM.7.j",
   "MOM.7.k",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.9.e"
  ]
 },
 "daycare": {
  "key": "daycare",
  "name": "Day Care",
  "group": "clinical",
  "pdfPage": 17,
  "inherits": null,
  "quickList": [
   "Initial assessment",
   "Nursing",
   "Narcotics",
   "Consents",
   "Medication management",
   "Monitoring after procedure"
  ],
  "kpis": [
   "PSQ 3d(30) Incidence of needle stick injury"
  ],
  "codes": [
   "AAC.4.a",
   "COP.7.a",
   "COP.7.d",
   "COP.7.f",
   "COP.7.g",
   "COP.12.b",
   "COP.13.d",
   "COP.13.h",
   "COP.14.c",
   "COP.14.d",
   "COP.14.f",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.9.e"
  ]
 },
 "dialysis": {
  "key": "dialysis",
  "name": "Dialysis Unit",
  "group": "clinical",
  "pdfPage": 18,
  "inherits": null,
  "quickList": [
   "Dialyzer re-use",
   "Medication management",
   "Medication orders",
   "Narcotics",
   "Medical gas",
   "Nursing care",
   "Documentation of hand-over",
   "Vulnerable patients",
   "Restraint policy",
   "Hazmat",
   "Equipment / furniture maintenance",
   "HIV testing",
   "Infection control",
   "Hand hygiene",
   "RO water, monthly endotoxin levels",
   "Informed consent",
   "Blood transfusion",
   "Case records — documentation",
   "Organ transplant awareness",
   "BMW",
   "Fire safety",
   "Patients' rights"
  ],
  "kpis": [
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(4) Percentage of medication charts with error prone abbreviations",
   "PSQ 3a(6) Percentage of patients developing ADRs",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(16) CLABSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 3d(32) Compliance rate to medication prescription in capitals",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses"
  ],
  "codes": [
   "COP.5.b",
   "COP.15.c",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "PRE.4.a",
   "PRE.4.d",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.8.b",
   "IPC.8.e",
   "FMS.2.d",
   "FMS.2.e",
   "FMS.2.f",
   "FMS.3.b",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.b",
   "FMS.4.d",
   "FMS.5.a",
   "FMS.5.b",
   "FMS.5.c",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e"
  ]
 },
 "icu": {
  "key": "icu",
  "name": "ICU, PICU, NICU, HDU",
  "group": "clinical",
  "pdfPage": 20,
  "inherits": null,
  "quickList": [
   "Initial assessment & reassessment",
   "Care plan",
   "Nursing care",
   "CPR",
   "Hand hygiene",
   "Infection control",
   "Safe transfer of patients",
   "Pain management",
   "Nutritional assessment",
   "Blood transfusion",
   "Vulnerable patients",
   "Patient feedback",
   "Medical gas",
   "End of life care",
   "Credentialing & privileging",
   "Equipment / furniture maintenance",
   "Quality assurance",
   "Adapt care bundles",
   "APACHE/SOFA scoring — standardised mortality rate",
   "Counselling by doctor",
   "Admission & discharge criteria",
   "Discharge & discharge summary",
   "Early warning signs",
   "Case records — documentation",
   "Documentation of hand-over",
   "Physician's sample drugs",
   "Medication orders",
   "Medication management",
   "Narcotics",
   "Restraint policy",
   "Hazmat",
   "Fire safety",
   "BMW",
   "Engineering controls",
   "Compressed air purity",
   "Referrals",
   "Patients' rights displayed",
   "Policy for bed shortage"
  ],
  "kpis": [
   "PSQ 3a(1) Time for initial assessment",
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(6) Percentage of patients developing ADRs",
   "PSQ 3a(8) Prevention of adverse events — wrong site, patient, surgery",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3a(9) Incidence of hospital associated pressure ulcers",
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(14) VAP",
   "PSQ 3b(15) CLABSI",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses",
   "PSQ 4c(24) Time taken for discharge",
   "PSQ 3a(11) Standardised mortality rate"
  ],
  "codes": [
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.d",
   "AAC.4.e",
   "AAC.4.f",
   "AAC.4.g",
   "AAC.5.a",
   "AAC.5.c",
   "AAC.5.d",
   "AAC.5.e",
   "AAC.12.a",
   "AAC.12.b",
   "AAC.12.c",
   "AAC.12.d",
   "AAC.12.e",
   "AAC.12.f",
   "AAC.12.g",
   "AAC.13.a",
   "AAC.13.b",
   "AAC.13.c",
   "AAC.13.d",
   "AAC.13.e",
   "COP.1.d",
   "COP.1.e",
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.6.a",
   "COP.6.b",
   "COP.6.c",
   "COP.6.d",
   "COP.6.e",
   "COP.6.f",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.8.b",
   "COP.8.c",
   "COP.8.d",
   "COP.8.g",
   "COP.9.a",
   "COP.9.b",
   "COP.9.c",
   "COP.9.d",
   "COP.9.e",
   "COP.9.f",
   "COP.9.g",
   "COP.11.a",
   "COP.11.b",
   "COP.11.c",
   "COP.11.d",
   "COP.11.e",
   "COP.11.f",
   "COP.11.g",
   "COP.11.h",
   "COP.12.a",
   "COP.12.b",
   "COP.12.c",
   "COP.12.d",
   "COP.12.e",
   "COP.12.f",
   "COP.12.g",
   "COP.12.h",
   "COP.14.a",
   "COP.14.b",
   "COP.14.c",
   "COP.14.d",
   "COP.16.a",
   "COP.16.d",
   "COP.16.e",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.19.a",
   "COP.19.b",
   "COP.19.c",
   "COP.19.d",
   "COP.19.e",
   "COP.20.a",
   "COP.20.b",
   "COP.20.c",
   "COP.20.d",
   "COP.20.e",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.8.a",
   "MOM.8.b",
   "MOM.8.c",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "PRE.1.a",
   "PRE.1.b",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.5.h",
   "PRE.5.i",
   "PRE.8.b",
   "PRE.8.c",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.8.b",
   "IPC.8.e",
   "FMS.2.d",
   "FMS.2.e",
   "FMS.2.f",
   "FMS.3.b",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.b",
   "FMS.4.d",
   "FMS.5.a",
   "FMS.5.b",
   "FMS.5.c",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.4.b",
   "IMS.4.c"
  ]
 },
 "ot": {
  "key": "ot",
  "name": "Operation Theatre",
  "group": "clinical",
  "pdfPage": 25,
  "inherits": null,
  "quickList": [
   "Anaesthesia assessment and plan",
   "Adverse anaesthesia events",
   "Prevention of wrong site/patient/procedure",
   "Blood transfusion",
   "Medical gas",
   "Compressed air purity",
   "Engineering controls",
   "Infection control",
   "Hand hygiene",
   "Sterilisation",
   "Re-use policy",
   "Fire safety",
   "Credentialing & privileging",
   "Post-operative care plan document",
   "Consents",
   "Vulnerable patients",
   "Medication management",
   "Medication orders",
   "Labelling of medicines",
   "Safe injection practice",
   "Narcotics",
   "Adequate equipment",
   "Equipment / furniture maintenance",
   "BMW",
   "Hazmat",
   "Patients' rights displayed",
   "Case records — documentation"
  ],
  "kpis": [
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(6) Percentage of patients developing ADRs",
   "PSQ 3a(7) Percentage of unplanned return to OT",
   "PSQ 3a(8) Prevention of adverse events — wrong site, patient, surgery",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3b(18) Appropriate prophylactic antibiotic within specified time frame",
   "PSQ 3b(19) Percentage of re-scheduling of surgeries",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 4c(25) Percentage of medical records having incomplete/improper consent",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses"
  ],
  "codes": [
   "COP.6.a",
   "COP.6.b",
   "COP.6.c",
   "COP.6.d",
   "COP.6.e",
   "COP.6.f",
   "COP.8.b",
   "COP.8.d",
   "COP.8.f",
   "COP.8.g",
   "COP.13.a",
   "COP.13.b",
   "COP.13.c",
   "COP.13.d",
   "COP.13.e",
   "COP.13.f",
   "COP.13.g",
   "COP.13.h",
   "COP.13.i",
   "COP.13.j",
   "COP.14.a",
   "COP.14.b",
   "COP.14.c",
   "COP.14.d",
   "COP.14.e",
   "COP.14.f",
   "COP.14.g",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.10.a",
   "MOM.10.b",
   "MOM.10.c",
   "MOM.10.d",
   "PRE.1.a",
   "PRE.1.b",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.5.h",
   "PRE.5.i",
   "PRE.6.a",
   "PRE.6.b",
   "PRE.6.c",
   "PRE.6.d",
   "PRE.8.b",
   "PRE.8.c",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.8.b",
   "IPC.8.e",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.2.e",
   "FMS.2.f",
   "FMS.3.b",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.b",
   "FMS.4.d",
   "FMS.5.a",
   "FMS.5.b",
   "FMS.5.c",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.4.d"
  ]
 },
 "recovery": {
  "key": "recovery",
  "name": "Recovery Room",
  "group": "clinical",
  "pdfPage": 28,
  "inherits": null,
  "quickList": [
   "Nursing care",
   "Pain management",
   "Blood transfusion",
   "Discharge criteria",
   "Infection control",
   "Medication management",
   "Restraint policy",
   "Hazmat",
   "CPR",
   "Documentation of hand-over",
   "Vulnerable patients",
   "Fire safety",
   "BMW",
   "Narcotics",
   "Medication orders",
   "Patients' rights",
   "Case records — documentation"
  ],
  "kpis": [],
  "codes": [
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.12.f",
   "COP.12.g",
   "COP.14.f",
   "COP.14.g",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.8.a",
   "MOM.8.b",
   "MOM.8.c",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d"
  ]
 },
 "endoscopy": {
  "key": "endoscopy",
  "name": "Endoscopy / Bronchoscopy",
  "group": "clinical",
  "pdfPage": 29,
  "inherits": null,
  "quickList": [
   "Safe transfer of patients",
   "Documentation of handing over",
   "Case records — documentation",
   "BMW",
   "Medication management",
   "Medication orders",
   "Medical gas",
   "Consents",
   "Patients' rights",
   "CPR",
   "Vulnerable patients",
   "Infection control",
   "Hand hygiene",
   "Narcotics",
   "Fire safety",
   "Equipment / furniture maintenance",
   "Sterilisation / disinfection",
   "Hazmat",
   "Procedure checklist",
   "Procedural sedation record"
  ],
  "kpis": [],
  "codes": [
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.12.a",
   "COP.12.b",
   "COP.12.c",
   "COP.12.d",
   "COP.12.e",
   "COP.12.f",
   "COP.12.g",
   "COP.12.h",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "PRE.4.d",
   "PRE.4.e",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.8.b",
   "IPC.8.e",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.2.e",
   "FMS.2.f",
   "FMS.3.b",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.b",
   "FMS.4.d",
   "FMS.5.a",
   "FMS.5.b",
   "FMS.5.c",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d"
  ]
 },
 "rehab": {
  "key": "rehab",
  "name": "Rehabilitation / Physiotherapy",
  "group": "clinical",
  "pdfPage": 31,
  "inherits": null,
  "quickList": [
   "Vulnerable patients",
   "Functional assessment",
   "Infection control",
   "Hazmat",
   "Equipment / furniture maintenance",
   "Clinical pathway",
   "Scope of department",
   "Biomedical waste management",
   "Patients' rights",
   "Case records — documentation",
   "Fire safety"
  ],
  "kpis": [],
  "codes": [
   "COP.16.a",
   "COP.16.b",
   "COP.16.c",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.18.a",
   "COP.18.b",
   "COP.18.c",
   "COP.18.d",
   "COP.18.e",
   "COP.18.f",
   "COP.18.g",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f"
  ]
 },
 "radiology": {
  "key": "radiology",
  "name": "Radiology",
  "group": "clinical",
  "pdfPage": 32,
  "inherits": null,
  "quickList": [
   "Statutory requirements",
   "TAT — critical alert not more than one hour",
   "Patient screening for safety",
   "PPE",
   "Patients' rights",
   "Medication management",
   "Hazmat",
   "BMW",
   "Quality assurance",
   "Safety precautions while transporting patients",
   "Radiation signages",
   "Recall / amendment of reports",
   "Safe transfer of patients",
   "Vulnerable patients",
   "Infection control",
   "MOU for outsourced investigations",
   "Equipment / furniture maintenance",
   "Fire safety",
   "Clinico-radiological meeting",
   "Appropriateness of investigation"
  ],
  "kpis": [
   "PSQ 3a(2) Number of reporting errors",
   "PSQ 3a(3) Percentage of adherence to safety precautions by staff working in diagnostics",
   "PSQ 4c(23) Waiting time for diagnostics"
  ],
  "codes": [
   "AAC.1.b",
   "AAC.1.c",
   "AAC.9.a",
   "AAC.9.b",
   "AAC.9.c",
   "AAC.9.d",
   "AAC.9.e",
   "AAC.9.f",
   "AAC.9.g",
   "AAC.9.h",
   "AAC.9.i",
   "AAC.9.j",
   "AAC.10.a",
   "AAC.10.b",
   "AAC.10.c",
   "AAC.10.d",
   "AAC.10.e",
   "AAC.10.f",
   "AAC.11.a",
   "AAC.11.b",
   "AAC.11.c",
   "AAC.11.d",
   "AAC.11.e",
   "COP.12.a",
   "COP.12.b",
   "COP.12.c",
   "COP.12.d",
   "COP.12.e",
   "COP.12.f",
   "COP.12.g",
   "COP.12.h",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "PRE.4.d",
   "IPC.3.d",
   "ROM.2.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f"
  ]
 },
 "nuclearmed": {
  "key": "nuclearmed",
  "name": "Nuclear Medicine",
  "group": "clinical",
  "pdfPage": 34,
  "inherits": null,
  "quickList": [
   "Statutory requirements",
   "Patient screening for safety",
   "PPE",
   "Patients' rights displayed",
   "Medication management",
   "Hazmat",
   "BMW",
   "Radiation signages",
   "Recall / amendment of reports",
   "Safe transfer of patients",
   "Vulnerable patients",
   "Infection control",
   "Equipment / furniture maintenance",
   "Fire safety",
   "Critical alert not more than one hour"
  ],
  "kpis": [
   "PSQ 3a(2) Number of reporting errors",
   "PSQ 3a(3) Percentage of adherence to safety precautions by staff working in diagnostics",
   "PSQ 4c(23) Waiting time for diagnostics"
  ],
  "codes": [
   "AAC.1.b",
   "AAC.1.c",
   "AAC.9.a",
   "AAC.9.b",
   "AAC.9.c",
   "AAC.9.d",
   "AAC.9.e",
   "AAC.9.f",
   "AAC.9.g",
   "AAC.9.h",
   "AAC.9.i",
   "AAC.9.j",
   "AAC.10.a",
   "AAC.10.b",
   "AAC.10.c",
   "AAC.10.d",
   "AAC.10.e",
   "AAC.10.f",
   "AAC.11.a",
   "AAC.11.b",
   "AAC.11.c",
   "AAC.11.d",
   "AAC.11.e",
   "COP.12.a",
   "COP.12.b",
   "COP.12.c",
   "COP.12.d",
   "COP.12.e",
   "COP.12.f",
   "COP.12.g",
   "COP.12.h",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.9.e",
   "PRE.4.d",
   "IPC.3.d",
   "ROM.2.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f"
  ]
 },
 "cathlab": {
  "key": "cathlab",
  "name": "Cardiac Catheterisation Lab",
  "group": "clinical",
  "pdfPage": 36,
  "inherits": null,
  "quickList": [
   "Statutory requirements",
   "Patient screening for safety",
   "CPR",
   "Moderate sedation",
   "Medication management",
   "Narcotics",
   "Reuse policy",
   "Case records — documentation",
   "Patients' rights displayed",
   "Radiation signages",
   "Recall / amendment of reports",
   "Safe transfer of patients",
   "Vulnerable patients",
   "Infection control",
   "Equipment / furniture maintenance",
   "Fire safety",
   "BMW",
   "Hazmat",
   "Procedural sedation record"
  ],
  "kpis": [
   "PSQ 3a(2) Number of reporting errors",
   "PSQ 3a(3) Percentage of adherence to safety precautions by staff working in diagnostics",
   "PSQ 4c(23) Waiting time for diagnostics"
  ],
  "codes": [
   "AAC.9.a",
   "AAC.9.b",
   "AAC.9.c",
   "AAC.9.d",
   "AAC.9.e",
   "AAC.9.f",
   "AAC.9.g",
   "AAC.9.h",
   "AAC.10.a",
   "AAC.10.b",
   "AAC.10.c",
   "AAC.10.d",
   "AAC.10.e",
   "AAC.11.a",
   "AAC.11.b",
   "AAC.11.c",
   "AAC.11.d",
   "AAC.11.e",
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.12.a",
   "COP.12.b",
   "COP.12.c",
   "COP.12.d",
   "COP.12.e",
   "COP.12.f",
   "COP.12.g",
   "COP.12.h",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.4.a",
   "MOM.4.b",
   "MOM.4.c",
   "MOM.4.d",
   "MOM.4.e",
   "MOM.4.f",
   "MOM.4.g",
   "MOM.4.h",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.10.a",
   "MOM.10.b",
   "MOM.10.c",
   "MOM.10.d",
   "PRE.4.d",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.8.b",
   "IPC.8.e",
   "ROM.2.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f"
  ]
 },
 "collection": {
  "key": "collection",
  "name": "Collection Centre (Lab)",
  "group": "clinical",
  "pdfPage": 38,
  "inherits": null,
  "quickList": [
   "Specimen transport",
   "PPE",
   "Spill management",
   "Hand hygiene",
   "Patient privacy",
   "Infection control",
   "Needle stick injuries"
  ],
  "kpis": [],
  "codes": [
   "AAC.6.e",
   "AAC.8.d",
   "AAC.8.e",
   "PRE.2.b",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.d",
   "FMS.3.e",
   "FMS.3.f"
  ]
 },
 "laboratory": {
  "key": "laboratory",
  "name": "Laboratory",
  "group": "clinical",
  "pdfPage": 39,
  "inherits": null,
  "quickList": [
   "TAT — critical alert not more than one hour",
   "Quality assurance",
   "MOU for outsourced investigations",
   "Spill management",
   "Equipment / furniture maintenance",
   "Immunisation of staff",
   "Patients' rights — respect for value and belief",
   "Clinicopathological meeting",
   "Test reports",
   "Recall / amendment of reports",
   "Lab safety",
   "PPE",
   "BMW",
   "Hazmat",
   "Fire safety",
   "Ensures quality of test results"
  ],
  "kpis": [
   "PSQ 3a(2) Number of reporting errors",
   "PSQ 3a(3) Percentage of adherence to safety precautions by staff working in diagnostics",
   "PSQ 4c(23) Waiting time for diagnostics"
  ],
  "codes": [
   "AAC.1.b",
   "AAC.1.c",
   "AAC.6.a",
   "AAC.6.b",
   "AAC.6.c",
   "AAC.6.d",
   "AAC.6.e",
   "AAC.6.f",
   "AAC.6.g",
   "AAC.6.h",
   "AAC.6.i",
   "AAC.6.j",
   "AAC.7.a",
   "AAC.7.b",
   "AAC.7.c",
   "AAC.7.d",
   "AAC.7.e",
   "AAC.7.f",
   "AAC.8.a",
   "AAC.8.b",
   "AAC.8.c",
   "AAC.8.d",
   "PRE.4.d",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.8.b",
   "IPC.8.e",
   "FMS.3.c",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "IMS.4.c"
  ]
 },
 "bloodbank": {
  "key": "bloodbank",
  "name": "Blood Bank and Transfusion Services",
  "group": "clinical",
  "pdfPage": 41,
  "inherits": null,
  "quickList": [
   "Statutory",
   "Transfusion committee",
   "Infection control",
   "Medication management",
   "Documentation",
   "Scope of transfusion service — MOU",
   "Quality assurance programme",
   "Turnaround time",
   "Biomedical waste management",
   "Hazmat",
   "Equipment / furniture maintenance",
   "Fire safety",
   "Rational use of blood and blood components"
  ],
  "kpis": [
   "PSQ 3a(9) Transfusion reactions",
   "PSQ 3c(20) Turnaround time for issue of blood and blood components"
  ],
  "codes": [
   "COP.8.a",
   "COP.8.b",
   "COP.8.c",
   "COP.8.d",
   "COP.8.e",
   "COP.8.f",
   "COP.8.g",
   "PRE.4.d",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.d",
   "IPC.8.b",
   "IPC.8.e",
   "ROM.2.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.6.e"
  ]
 },
 "radiotherapy": {
  "key": "radiotherapy",
  "name": "Radiotherapy / Radioactive Drugs",
  "group": "clinical",
  "pdfPage": 42,
  "inherits": null,
  "quickList": [
   "Statutory requirements",
   "Patient screening for safety",
   "PPE",
   "Patients' rights — respect for patient and safety",
   "Medication management",
   "Hazmat",
   "BMW",
   "Quality assurance",
   "Case records — documentation",
   "Radiation signages",
   "Recall / amendment of reports",
   "Safe transfer of patients",
   "Vulnerable patients",
   "Infection control",
   "MOU for outsourced investigations",
   "Equipment / furniture maintenance",
   "Fire safety"
  ],
  "kpis": [],
  "codes": [
   "AAC.1.b",
   "AAC.1.c",
   "AAC.9.a",
   "AAC.9.b",
   "AAC.9.c",
   "AAC.9.d",
   "AAC.9.e",
   "AAC.9.f",
   "AAC.9.g",
   "AAC.9.h",
   "AAC.9.i",
   "AAC.9.j",
   "AAC.10.a",
   "AAC.10.b",
   "AAC.10.c",
   "AAC.10.d",
   "AAC.10.e",
   "AAC.10.f",
   "AAC.11.a",
   "AAC.11.b",
   "AAC.11.c",
   "AAC.11.d",
   "AAC.11.e",
   "COP.12.a",
   "COP.12.b",
   "COP.12.c",
   "COP.12.d",
   "COP.12.e",
   "COP.12.f",
   "COP.12.g",
   "COP.12.h",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "PRE.4.d",
   "IPC.3.d",
   "ROM.2.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f"
  ]
 },
 "nutrition": {
  "key": "nutrition",
  "name": "Nutrition Therapy",
  "group": "clinical",
  "pdfPage": 44,
  "inherits": null,
  "quickList": [
   "Nutritional assessment & reassessment",
   "Safe storage and distribution of food",
   "Capturing of quality indicator data",
   "Patient family education",
   "Maternal & paediatric nutritional assessment",
   "Documentation",
   "Patient interviews"
  ],
  "kpis": [],
  "codes": [
   "AAC.4.a",
   "AAC.4.b",
   "AAC.4.c",
   "AAC.4.d",
   "AAC.4.e",
   "AAC.4.f",
   "AAC.4.g",
   "COP.10.e",
   "COP.11.g",
   "COP.19.a",
   "COP.19.b",
   "COP.19.c",
   "COP.19.d",
   "COP.19.e",
   "PRE.5.c",
   "PRE.5.d"
  ]
 },
 "infectioncontrol": {
  "key": "infectioncontrol",
  "name": "Hospital Infection Control",
  "group": "clinical",
  "pdfPage": 45,
  "inherits": null,
  "quickList": [
   "Documented HIC programme",
   "High risk areas & surveillance",
   "Antibiotic policy",
   "Hand hygiene",
   "Isolation policy",
   "HIC budget",
   "Immunisation policy",
   "Work restriction policy for staff with transmissible infections",
   "ICO, ICN",
   "HAIs",
   "BMW",
   "Pre / post exposure prophylaxis",
   "Outbreaks",
   "Training",
   "Post exposure prophylaxis"
  ],
  "kpis": [
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(14) VAP",
   "PSQ 3b(15) CLABSI",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury"
  ],
  "codes": [
   "IPC.1.a",
   "IPC.1.b",
   "IPC.1.c",
   "IPC.1.d",
   "IPC.1.e",
   "IPC.1.f",
   "IPC.1.g",
   "IPC.1.h",
   "IPC.1.i",
   "IPC.1.j",
   "IPC.2.a",
   "IPC.2.b",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.6.a",
   "IPC.6.b",
   "IPC.6.c",
   "IPC.6.d",
   "IPC.6.e",
   "IPC.6.f",
   "IPC.6.g",
   "IPC.6.h",
   "IPC.6.i",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.7.d",
   "IPC.7.e",
   "IPC.8.a",
   "IPC.8.b",
   "IPC.8.c",
   "IPC.8.d",
   "IPC.8.e"
  ]
 },
 "transplant": {
  "key": "transplant",
  "name": "Organ Transplant",
  "group": "clinical",
  "pdfPage": 47,
  "inherits": null,
  "quickList": [
   "Legal requirements",
   "Informed consents",
   "Qualified counsellors",
   "Transplant ICU",
   "Policies & procedures",
   "Creating awareness",
   "Privileging"
  ],
  "kpis": [],
  "codes": [
   "COP.9.a",
   "COP.9.b",
   "COP.9.c",
   "COP.9.d",
   "COP.9.e",
   "COP.9.f",
   "COP.9.g",
   "COP.15.a",
   "COP.15.b",
   "COP.15.c",
   "COP.15.d",
   "ROM.2.b",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f"
  ]
 },
 "dental": {
  "key": "dental",
  "name": "Dental",
  "group": "clinical",
  "pdfPage": 48,
  "inherits": null,
  "quickList": [
   "Initial assessment & reassessment",
   "Pain management",
   "Vulnerable patients",
   "Medication orders",
   "Medication management",
   "Hazmat",
   "Equipment / furniture maintenance",
   "Safe transfer of patients",
   "Infection control",
   "CPR",
   "Case records — documentation",
   "Patients' rights",
   "Fire safety",
   "BMW"
  ],
  "kpis": [],
  "codes": [
   "AAC.9.a",
   "AAC.11.a",
   "AAC.11.b",
   "AAC.11.c",
   "AAC.11.d",
   "AAC.11.e",
   "COP.5.a",
   "COP.5.b",
   "COP.5.e",
   "COP.7.a",
   "COP.7.b",
   "COP.7.c",
   "COP.7.d",
   "COP.7.e",
   "COP.7.f",
   "COP.7.g",
   "COP.12.a",
   "COP.12.b",
   "COP.12.c",
   "COP.12.d",
   "COP.12.e",
   "COP.12.f",
   "COP.12.g",
   "COP.12.h",
   "COP.18.a",
   "COP.18.b",
   "COP.18.c",
   "COP.18.d",
   "COP.18.e",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.10.a",
   "MOM.10.b",
   "MOM.10.c",
   "MOM.10.d",
   "PRE.1.a",
   "PRE.1.b",
   "PRE.1.d",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.2.k",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.5.h",
   "PRE.5.i",
   "PRE.6.a",
   "PRE.6.b",
   "PRE.6.c",
   "PRE.6.d",
   "PRE.8.b",
   "PRE.8.c",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "IPC.4.a",
   "IPC.4.b",
   "IPC.4.c",
   "IPC.4.d",
   "IPC.4.e",
   "IPC.4.f",
   "IPC.5.a",
   "IPC.5.b",
   "IPC.5.c",
   "IPC.5.d",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.8.b",
   "IPC.8.e",
   "ROM.2.b",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.2.e",
   "FMS.2.f",
   "FMS.3.b",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.4.b",
   "FMS.4.d",
   "FMS.5.a",
   "FMS.5.b",
   "FMS.5.c",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "IMS.3.a",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.4.d"
  ]
 },
 "nursing": {
  "key": "nursing",
  "name": "Nursing",
  "group": "clinical",
  "pdfPage": 50,
  "inherits": null,
  "quickList": [
   "Nursing manual — clinical pathway",
   "Adequacy of nursing staff",
   "Manpower planning",
   "Privileging",
   "Credentialing",
   "Contingency plan for shortfall in nurses",
   "Competent nurses in high risk obstetrics & paediatric services",
   "Monitoring of nursing services & KPIs",
   "Nurses part of CPR, safety and HIC committee",
   "Appropriate & adequate equipment",
   "Nursing initial assessment",
   "Reassessment",
   "Aligned care plan",
   "Structured handover",
   "Clinical audits",
   "Nursing empowerment",
   "Training in CPR — ICU",
   "Provided with adequate equipment",
   "Patient feedback to include nursing care",
   "Documentation of monitoring and all nursing activities"
  ],
  "kpis": [
   "PSQ 3a(1) Time for initial assessment",
   "PSQ 3a(4) Medication error rate",
   "PSQ 3a(8) Prevention of adverse events — wrong site, patient, surgery",
   "PSQ 3a(9) Percentage of transfusion reactions",
   "PSQ 3a(9) Incidence of hospital associated pressure ulcers after admission",
   "PSQ 3b(13) CAUTI",
   "PSQ 3b(14) VAP",
   "PSQ 3b(15) CLABSI",
   "PSQ 3b(16) SSI",
   "PSQ 3b(17) Hand hygiene compliance rate",
   "PSQ 3c(21) Nurse patient ratio",
   "PSQ 3d(30) Incidence of needle stick injury",
   "PSQ 3d(31) Appropriate handover during shift change",
   "PSQ 4d(28) Patient fall rate",
   "PSQ 4d(29) Percentage of near-misses"
  ],
  "codes": [
   "AAC.1.b",
   "AAC.4.a",
   "AAC.4.d",
   "AAC.5.d",
   "AAC.12.a",
   "AAC.12.c",
   "AAC.12.d",
   "COP.5.a",
   "COP.5.b",
   "COP.5.d",
   "COP.6.a",
   "COP.6.b",
   "COP.6.c",
   "COP.6.d",
   "COP.6.e",
   "COP.6.f",
   "COP.9.c",
   "COP.10.g",
   "COP.11.f",
   "PRE.7.a",
   "PRE.7.b",
   "PRE.7.c",
   "PRE.7.d",
   "PRE.7.e",
   "PRE.7.f",
   "IPC.1.a",
   "PSQ.1.a",
   "PSQ.1.b",
   "PSQ.1.c",
   "PSQ.1.d",
   "PSQ.1.e",
   "PSQ.1.f",
   "PSQ.1.g",
   "PSQ.2.a",
   "PSQ.2.b",
   "PSQ.2.c",
   "PSQ.2.d",
   "PSQ.2.e",
   "PSQ.2.f",
   "PSQ.2.g",
   "PSQ.2.h",
   "PSQ.2.i",
   "PSQ.3.a",
   "PSQ.3.b",
   "PSQ.3.c",
   "PSQ.3.d",
   "PSQ.3.e",
   "PSQ.3.f",
   "PSQ.3.g",
   "PSQ.3.h",
   "PSQ.5.a",
   "PSQ.5.b",
   "PSQ.5.c",
   "PSQ.5.d",
   "PSQ.5.e",
   "PSQ.5.f",
   "HRM.1.a",
   "HRM.1.b",
   "HRM.1.c",
   "HRM.1.d",
   "HRM.1.e",
   "HRM.1.f",
   "HRM.1.g",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f"
  ]
 },
 "documentreview": {
  "key": "documentreview",
  "name": "Document Review",
  "group": "nonclinical",
  "pdfPage": 54,
  "inherits": null,
  "quickList": [
   "Vision, mission, values",
   "HIC manual",
   "Updation of manuals",
   "Licences",
   "Apex manual",
   "Safety manual",
   "Organogram",
   "Document control",
   "NABH application form contents",
   "Self-assessment checklist",
   "Internal assessment report",
   "Scope of services of the organisation"
  ],
  "kpis": [],
  "codes": [
   "IPC.2.a",
   "IPC.2.b",
   "IPC.2.c",
   "IPC.2.d",
   "PSQ.1.a",
   "PSQ.1.b",
   "PSQ.1.c",
   "PSQ.1.d",
   "PSQ.1.e",
   "PSQ.1.f",
   "PSQ.1.g",
   "PSQ.2.a",
   "PSQ.2.b",
   "PSQ.2.c",
   "PSQ.2.d",
   "PSQ.2.e",
   "PSQ.2.f",
   "PSQ.2.g",
   "PSQ.2.h",
   "PSQ.2.i",
   "PSQ.7.a",
   "PSQ.7.b",
   "PSQ.7.c",
   "PSQ.7.d",
   "PSQ.7.e",
   "PSQ.7.f",
   "ROM.1.a",
   "ROM.1.b",
   "ROM.1.c",
   "ROM.1.d",
   "ROM.1.e",
   "ROM.1.f",
   "ROM.1.g",
   "ROM.1.h",
   "ROM.1.i",
   "ROM.4.a",
   "ROM.4.b",
   "ROM.4.c",
   "ROM.4.d",
   "ROM.4.e",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "IMS.6.a"
  ]
 },
 "qualitymgmt": {
  "key": "qualitymgmt",
  "name": "Quality Management",
  "group": "nonclinical",
  "pdfPage": 55,
  "inherits": null,
  "quickList": [
   "QIP committee",
   "Quality assurance (emergency, lab, ICU, OT)",
   "Capturing of quality indicator data",
   "Quality improvement targets & tools",
   "Incidents and sentinel events",
   "Clinical & patient safety officer",
   "PROM",
   "Table top",
   "Safety programme",
   "Internal audits",
   "Validation of data",
   "Staff & patient interviews",
   "Clinical audits",
   "Analysis of patient safety risks",
   "Feedback to implement patient safety & QIP"
  ],
  "kpis": [],
  "codes": [
   "MOM.4.e",
   "PSQ.1.a",
   "PSQ.1.b",
   "PSQ.1.c",
   "PSQ.1.d",
   "PSQ.1.e",
   "PSQ.1.f",
   "PSQ.1.g",
   "PSQ.2.a",
   "PSQ.2.b",
   "PSQ.2.c",
   "PSQ.2.d",
   "PSQ.2.e",
   "PSQ.2.f",
   "PSQ.2.g",
   "PSQ.2.h",
   "PSQ.2.i",
   "PSQ.3.a",
   "PSQ.3.b",
   "PSQ.3.c",
   "PSQ.3.d",
   "PSQ.3.e",
   "PSQ.3.f",
   "PSQ.3.g",
   "PSQ.3.h",
   "PSQ.4.a",
   "PSQ.4.b",
   "PSQ.4.c",
   "PSQ.4.d",
   "PSQ.5.a",
   "PSQ.5.b",
   "PSQ.5.c",
   "PSQ.5.d",
   "PSQ.5.e",
   "PSQ.5.f",
   "PSQ.6.a",
   "PSQ.6.b",
   "PSQ.6.c",
   "PSQ.6.d",
   "PSQ.6.e",
   "PSQ.6.f",
   "PSQ.7.a",
   "PSQ.7.b",
   "PSQ.7.c",
   "PSQ.7.d",
   "PSQ.7.e",
   "PSQ.7.f",
   "IMS.2.e"
  ]
 },
 "management": {
  "key": "management",
  "name": "Top Management / ROM Interview",
  "group": "nonclinical",
  "pdfPage": 58,
  "inherits": null,
  "quickList": [
   "Operational & strategic planning",
   "Actions on recommendations of committees",
   "Risk management",
   "Ethical management",
   "Mechanism to update statutory requirements",
   "Support for quality, infection control"
  ],
  "kpis": [],
  "codes": [
   "PRE.1.c",
   "PRE.1.e",
   "IPC.1.a",
   "IPC.1.b",
   "IPC.1.c",
   "IPC.1.d",
   "IPC.1.e",
   "IPC.1.f",
   "IPC.1.g",
   "IPC.1.h",
   "IPC.1.i",
   "IPC.1.j",
   "IPC.2.b",
   "PSQ.2.c",
   "PSQ.2.d",
   "PSQ.2.e",
   "PSQ.2.f",
   "ROM.1.a",
   "ROM.1.b",
   "ROM.1.c",
   "ROM.1.d",
   "ROM.1.e",
   "ROM.1.f",
   "ROM.1.g",
   "ROM.1.h",
   "ROM.1.i",
   "ROM.2.a",
   "ROM.2.b",
   "ROM.2.c",
   "ROM.2.d",
   "ROM.3.a",
   "ROM.3.b",
   "ROM.3.c",
   "ROM.3.d",
   "ROM.3.e",
   "ROM.3.f",
   "ROM.3.g",
   "ROM.4.a",
   "ROM.4.b",
   "ROM.4.c",
   "ROM.4.d",
   "ROM.4.e",
   "ROM.5.a",
   "ROM.5.b",
   "ROM.5.c",
   "ROM.5.d",
   "ROM.5.e",
   "ROM.5.f",
   "HRM.5.a",
   "HRM.5.b",
   "HRM.5.c",
   "HRM.5.d",
   "HRM.5.e",
   "HRM.5.f",
   "HRM.6.a",
   "HRM.6.b",
   "HRM.6.c",
   "HRM.6.d",
   "HRM.6.e",
   "HRM.6.f",
   "HRM.6.g",
   "HRM.8.a",
   "HRM.8.b",
   "HRM.8.c",
   "HRM.8.d",
   "HRM.8.e",
   "HRM.8.f",
   "HRM.9.a",
   "HRM.9.b",
   "HRM.9.c",
   "HRM.9.d"
  ]
 },
 "committees": {
  "key": "committees",
  "name": "Committees",
  "group": "nonclinical",
  "pdfPage": 60,
  "inherits": null,
  "quickList": [
   "Scope",
   "Frequency of meetings as per SOP",
   "Composition of committee",
   "Action taken on recommendations",
   "Minutes of meetings"
  ],
  "kpis": [],
  "codes": [
   "COP.5.c",
   "COP.5.d",
   "COP.5.e",
   "MOM.1.c",
   "MOM.2.a",
   "MOM.2.b",
   "MOM.8.a",
   "MOM.8.b",
   "MOM.8.c",
   "MOM.8.d",
   "MOM.8.e",
   "MOM.8.f",
   "IPC.1.c",
   "PSQ.2.a",
   "PSQ.2.b",
   "PSQ.2.c",
   "PSQ.2.d",
   "PSQ.2.e",
   "PSQ.2.f",
   "PSQ.2.g",
   "PSQ.2.h",
   "PSQ.2.i",
   "PSQ.5.a",
   "PSQ.5.b",
   "PSQ.5.c",
   "PSQ.5.d",
   "PSQ.5.e",
   "PSQ.5.f",
   "ROM.1.f",
   "ROM.6.d",
   "FMS.1.a",
   "FMS.1.b",
   "HRM.8.d",
   "IMS.2.a",
   "IMS.3.f",
   "IMS.7.c",
   "IMS.7.d",
   "IMS.7.e",
   "IMS.7.f",
   "IMS.7.g"
  ]
 },
 "hr": {
  "key": "hr",
  "name": "Human Resource Department",
  "group": "nonclinical",
  "pdfPage": 61,
  "inherits": null,
  "quickList": [
   "HR planning",
   "Training & development",
   "Appraisal",
   "Health needs",
   "Credentialing & privileging",
   "Recruitment procedure",
   "Training on safety",
   "Disciplinary & grievance",
   "Personal file",
   "Job description"
  ],
  "kpis": [
   "PSQ 4e(i) Employee satisfaction index",
   "PSQ 4e(ii) Employee attrition rate",
   "PSQ 4e(iii) Absenteeism rate",
   "PSQ 4e(iv) Percentage of employees aware of employee rights & responsibilities"
  ],
  "codes": [
   "HRM.1.a",
   "HRM.1.b",
   "HRM.1.c",
   "HRM.1.d",
   "HRM.1.e",
   "HRM.1.f",
   "HRM.1.g",
   "HRM.2.a",
   "HRM.2.b",
   "HRM.2.c",
   "HRM.2.d",
   "HRM.3.a",
   "HRM.3.b",
   "HRM.3.c",
   "HRM.3.d",
   "HRM.3.e",
   "HRM.3.f",
   "HRM.3.g",
   "HRM.3.h",
   "HRM.3.i",
   "HRM.4.a",
   "HRM.4.b",
   "HRM.4.c",
   "HRM.4.d",
   "HRM.4.e",
   "HRM.4.f",
   "HRM.5.a",
   "HRM.5.b",
   "HRM.5.c",
   "HRM.5.d",
   "HRM.5.e",
   "HRM.5.f",
   "HRM.6.a",
   "HRM.6.b",
   "HRM.6.c",
   "HRM.6.d",
   "HRM.6.e",
   "HRM.6.f",
   "HRM.6.g",
   "HRM.7.a",
   "HRM.7.b",
   "HRM.7.c",
   "HRM.7.d",
   "HRM.7.e",
   "HRM.8.a",
   "HRM.8.b",
   "HRM.8.c",
   "HRM.8.d",
   "HRM.8.e",
   "HRM.8.f",
   "HRM.9.a",
   "HRM.9.b",
   "HRM.9.c",
   "HRM.9.d",
   "HRM.10.a",
   "HRM.10.b",
   "HRM.10.c",
   "HRM.10.d",
   "HRM.11.a",
   "HRM.11.b",
   "HRM.11.c",
   "HRM.11.d",
   "HRM.11.e",
   "HRM.11.f",
   "HRM.12.a",
   "HRM.12.b",
   "HRM.12.c",
   "HRM.12.d",
   "HRM.12.e",
   "HRM.12.f",
   "HRM.13.a",
   "HRM.13.b",
   "HRM.13.c",
   "HRM.13.d",
   "HRM.13.e"
  ]
 },
 "mrd": {
  "key": "mrd",
  "name": "Medical Record Department",
  "group": "nonclinical",
  "pdfPage": 64,
  "inherits": null,
  "quickList": [
   "Security & confidentiality",
   "Destruction of case records",
   "Medical record audit",
   "Transfer notes",
   "Birth and death report",
   "Retention policy",
   "System for access to records",
   "Case records sampling",
   "Statutory documents",
   "Fire safety"
  ],
  "kpis": [
   "PSQ 4g(i) Records not having discharge summary",
   "PSQ 4g(ii) Records not ICD codified",
   "PSQ 4g(iii) Records with incomplete consents",
   "PSQ 4g(iv) Percentage of missing records"
  ],
  "codes": [
   "AAC.4.f",
   "AAC.13.a",
   "AAC.13.b",
   "AAC.13.c",
   "AAC.13.d",
   "AAC.13.e",
   "COP.11.f",
   "COP.11.h",
   "COP.14.d",
   "COP.14.f",
   "COP.14.g",
   "IPC.3.a",
   "IPC.3.b",
   "IPC.3.c",
   "IPC.3.d",
   "IPC.3.e",
   "IPC.3.f",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e",
   "IMS.3.a",
   "IMS.3.b",
   "IMS.3.c",
   "IMS.3.d",
   "IMS.3.e",
   "IMS.3.f",
   "IMS.3.g",
   "IMS.4.a",
   "IMS.4.b",
   "IMS.4.c",
   "IMS.4.d",
   "IMS.4.e",
   "IMS.4.f",
   "IMS.4.g",
   "IMS.4.h",
   "IMS.5.a",
   "IMS.5.b",
   "IMS.5.c",
   "IMS.5.d",
   "IMS.5.e",
   "IMS.5.f",
   "IMS.6.a",
   "IMS.6.b",
   "IMS.6.c",
   "IMS.6.d",
   "IMS.7.a",
   "IMS.7.b",
   "IMS.7.c",
   "IMS.7.d",
   "IMS.7.e",
   "IMS.7.f",
   "IMS.7.g"
  ]
 },
 "his": {
  "key": "his",
  "name": "Hospital Information System",
  "group": "nonclinical",
  "pdfPage": 66,
  "inherits": null,
  "quickList": [
   "Maintenance plan",
   "Disaster back-up",
   "Confidentiality",
   "Retention policy",
   "Fire safety",
   "Licences",
   "Telemedicine",
   "Access to patients' data",
   "Destruction of data"
  ],
  "kpis": [],
  "codes": [
   "FMS.3.f",
   "IMS.1.a",
   "IMS.1.b",
   "IMS.1.c",
   "IMS.1.d",
   "IMS.1.e",
   "IMS.1.f",
   "IMS.1.g",
   "IMS.2.a",
   "IMS.2.b",
   "IMS.2.c",
   "IMS.2.d",
   "IMS.2.e",
   "IMS.5.a",
   "IMS.5.b",
   "IMS.5.c",
   "IMS.5.d",
   "IMS.5.e",
   "IMS.5.f",
   "IMS.6.a",
   "IMS.6.b",
   "IMS.6.c",
   "IMS.6.d"
  ]
 },
 "frontoffice": {
  "key": "frontoffice",
  "name": "Front Office, Registration, Admission & Billing",
  "group": "nonclinical",
  "pdfPage": 67,
  "inherits": null,
  "quickList": [
   "Scope of services",
   "Registration",
   "Admission process",
   "Patients' rights display",
   "Generation of UHID",
   "Feedback / complaints"
  ],
  "kpis": [
   "PSQ 4d(iii) Waiting time for OP consultation"
  ],
  "codes": [
   "AAC.1.a",
   "AAC.1.b",
   "AAC.1.c",
   "AAC.1.d",
   "AAC.2.a",
   "AAC.2.b",
   "AAC.2.c",
   "AAC.2.d",
   "AAC.2.e",
   "COP.10.b",
   "COP.11.b",
   "COP.16.a",
   "PRE.1.a",
   "PRE.1.d",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.4.b",
   "PRE.4.c",
   "PRE.6.a",
   "PRE.6.b",
   "PRE.6.c",
   "PRE.7.a",
   "PRE.7.b",
   "PRE.7.c",
   "PRE.7.d",
   "PRE.7.e",
   "PRE.7.f",
   "ROM.2.a",
   "FMS.1.b",
   "FMS.2.c"
  ]
 },
 "biomedical": {
  "key": "biomedical",
  "name": "Biomedical Equipment Management, Medical Gases, Vacuum",
  "group": "nonclinical",
  "pdfPage": 68,
  "inherits": null,
  "quickList": [
   "Equipment planning",
   "Qualified staff",
   "Condemnation & disposal",
   "Storage of medical gas",
   "Operational & maintenance plan",
   "Inventory",
   "PM, calibration",
   "Colour coding",
   "Compressed air purity"
  ],
  "kpis": [],
  "codes": [
   "FMS.4.a",
   "FMS.4.b",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.4.e",
   "FMS.4.f",
   "FMS.4.g",
   "FMS.4.h",
   "FMS.5.a",
   "FMS.5.b",
   "FMS.5.c",
   "FMS.5.d",
   "FMS.5.e",
   "FMS.5.f",
   "FMS.5.g",
   "FMS.5.h"
  ]
 },
 "pharmacy": {
  "key": "pharmacy",
  "name": "Pharmacy and Pharmacy Store",
  "group": "nonclinical",
  "pdfPage": 69,
  "inherits": null,
  "quickList": [
   "Pharmacy licence",
   "Storage",
   "Formulary",
   "Emergency medications",
   "Safe dispensing",
   "Fire safety",
   "Duty roster of pharmacists",
   "Inventory",
   "LASA",
   "High risk medications",
   "Narcotics"
  ],
  "kpis": [
   "PSQ 4a(i) Percentage of drugs/consumables procured by local purchase",
   "PSQ 4a(ii) Percentage of stockouts",
   "PSQ 4a(iii) Percentage of drugs/consumables rejected before GRN",
   "PSQ 4a(iv) Percentage of variations from procurement process"
  ],
  "codes": [
   "MOM.1.a",
   "MOM.1.b",
   "MOM.1.d",
   "MOM.2.a",
   "MOM.2.c",
   "MOM.2.d",
   "MOM.2.e",
   "MOM.3.a",
   "MOM.3.b",
   "MOM.3.c",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.6.a",
   "MOM.6.b",
   "MOM.6.c",
   "MOM.6.d",
   "MOM.6.e",
   "MOM.6.f",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.d",
   "MOM.11.a",
   "MOM.11.b",
   "MOM.11.c",
   "MOM.11.d",
   "MOM.11.e"
  ]
 },
 "purchase": {
  "key": "purchase",
  "name": "Purchase, Stores & Materials Management",
  "group": "nonclinical",
  "pdfPage": 70,
  "inherits": null,
  "quickList": [
   "Drugs",
   "Implants & prosthesis",
   "Planning",
   "Acquisition",
   "Consumables",
   "Equipment",
   "Selection",
   "Disposal"
  ],
  "kpis": [
   "PSQ 4a(i) Percentage of consumables procured by local purchase",
   "PSQ 4a(ii) Percentage of stockouts",
   "PSQ 4a(iii) Percentage of consumables rejected before GRN",
   "PSQ 4a(iv) Percentage of variations from procurement process"
  ],
  "codes": [
   "MOM.2.d",
   "MOM.2.e",
   "MOM.11.a",
   "MOM.11.b",
   "MOM.11.c",
   "MOM.11.d",
   "FMS.3.a",
   "FMS.3.b",
   "FMS.4.a",
   "FMS.4.b",
   "FMS.4.g"
  ]
 },
 "facility": {
  "key": "facility",
  "name": "Facility Management: Engineering and Maintenance",
  "group": "nonclinical",
  "pdfPage": 71,
  "inherits": null,
  "quickList": [
   "Licences",
   "Signages",
   "Controlled access",
   "Water & electricity maintenance and alternate sources",
   "Manifold room",
   "Engineering controls",
   "Safety education programme",
   "Airconditioning",
   "Fire safety",
   "Up to date drawings",
   "Provision of space",
   "Designated individuals",
   "Furniture maintenance",
   "STP",
   "Safety devices",
   "PM & calibration of equipment",
   "Green measures"
  ],
  "kpis": [],
  "codes": [
   "COP.14.j",
   "ROM.2.a",
   "ROM.2.b",
   "ROM.2.c",
   "ROM.2.d",
   "FMS.1.a",
   "FMS.1.b",
   "FMS.1.c",
   "FMS.1.d",
   "FMS.1.e",
   "FMS.2.a",
   "FMS.2.b",
   "FMS.2.c",
   "FMS.2.d",
   "FMS.2.e",
   "FMS.2.f",
   "FMS.3.a",
   "FMS.3.b",
   "FMS.3.c",
   "FMS.3.d",
   "FMS.3.e",
   "FMS.3.f",
   "FMS.6.a",
   "FMS.6.b",
   "FMS.6.c",
   "FMS.6.d",
   "FMS.6.e"
  ]
 },
 "safety": {
  "key": "safety",
  "name": "Safety Programme",
  "group": "nonclinical",
  "pdfPage": 72,
  "inherits": null,
  "quickList": [
   "Safety committee",
   "Identify opportunities for improvement activities",
   "Patient safety devices",
   "Disposal of non functioning items",
   "Fire fighting equipment & personnel",
   "Hazmat",
   "MSDS",
   "Patient safety goals",
   "Emergency situations identified",
   "Facility rounds",
   "Fire plans",
   "Mock drills",
   "Spill management"
  ],
  "kpis": [],
  "codes": [
   "PSQ.1.a",
   "PSQ.1.b",
   "PSQ.1.c",
   "PSQ.1.d",
   "PSQ.1.e",
   "PSQ.1.f",
   "PSQ.1.g",
   "FMS.1.a",
   "FMS.1.b",
   "FMS.1.c",
   "FMS.1.d",
   "FMS.1.e",
   "FMS.3.e",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e"
  ]
 },
 "housekeeping": {
  "key": "housekeeping",
  "name": "Housekeeping",
  "group": "nonclinical",
  "pdfPage": 73,
  "inherits": null,
  "quickList": [
   "Surveillance",
   "Biomedical waste handling",
   "Checklist",
   "Hazmat"
  ],
  "kpis": [],
  "codes": [
   "IPC.2.c",
   "IPC.4.c",
   "IPC.4.d",
   "FMS.3.e"
  ]
 },
 "laundry": {
  "key": "laundry",
  "name": "Laundry and Linen",
  "group": "nonclinical",
  "pdfPage": 74,
  "inherits": null,
  "quickList": [
   "Layout/space of laundry",
   "Hazmat",
   "Soiled linen",
   "Policy for change of linen",
   "If outsourced quality assurance",
   "Fire safety",
   "Machinery maintenance plan",
   "Washing protocols",
   "Linen segregation",
   "Infection control",
   "Machine maintenance"
  ],
  "kpis": [],
  "codes": [
   "IPC.4.e",
   "ROM.5.f",
   "FMS.2.b",
   "FMS.3.c",
   "FMS.3.e",
   "FMS.4.c",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e"
  ]
 },
 "kitchen": {
  "key": "kitchen",
  "name": "Kitchen / Canteen",
  "group": "nonclinical",
  "pdfPage": 75,
  "inherits": null,
  "quickList": [
   "Preparation of food",
   "Washing facility",
   "Health check-up of staff",
   "Fire safety",
   "Storage & distribution",
   "Food handlers screening",
   "Machine maintenance"
  ],
  "kpis": [],
  "codes": [
   "IPC.4.f",
   "IPC.8.b",
   "ROM.3.c",
   "ROM.5.f",
   "FMS.3.c",
   "FMS.4.c",
   "FMS.7.a",
   "FMS.7.b",
   "FMS.7.c",
   "FMS.7.d",
   "FMS.7.e"
  ]
 },
 "mortuary": {
  "key": "mortuary",
  "name": "Mortuary",
  "group": "nonclinical",
  "pdfPage": 76,
  "inherits": null,
  "quickList": [
   "Mortuary facilities",
   "Infection control",
   "Machine maintenance"
  ],
  "kpis": [],
  "codes": [
   "IPC.2.a",
   "IPC.2.b",
   "IPC.2.c",
   "IPC.2.d",
   "IPC.4.c",
   "ROM.5.f",
   "FMS.3.c",
   "FMS.4.c"
  ]
 },
 "cssd": {
  "key": "cssd",
  "name": "CSSD",
  "group": "nonclinical",
  "pdfPage": 77,
  "inherits": null,
  "quickList": [
   "Cleaning & disinfection",
   "Policies & procedures",
   "Validation",
   "ETO safety",
   "Staff training",
   "Space & zoning",
   "Reprocessing of instruments",
   "Recall procedure",
   "Reuse policy",
   "Machine"
  ],
  "kpis": [],
  "codes": [
   "IPC.1.b",
   "IPC.3.a",
   "IPC.4.a",
   "IPC.4.c",
   "IPC.7.a",
   "IPC.7.b",
   "IPC.7.c",
   "IPC.7.d",
   "IPC.7.e",
   "FMS.4.b",
   "FMS.4.c",
   "FMS.4.d",
   "FMS.5.d",
   "FMS.5.e"
  ]
 }
};

window.AUDIT_INTERVIEWS = {
 "patient": {
  "label": "Patient and family interview",
  "codes": [
   "AAC.5.b",
   "AAC.13.a",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.19.a",
   "COP.19.b",
   "COP.19.c",
   "COP.19.d",
   "COP.19.e",
   "MOM.11.d",
   "PRE.1.b",
   "PRE.2.a",
   "PRE.2.b",
   "PRE.2.c",
   "PRE.2.d",
   "PRE.2.e",
   "PRE.2.f",
   "PRE.2.g",
   "PRE.2.h",
   "PRE.2.i",
   "PRE.2.j",
   "PRE.3.a",
   "PRE.3.b",
   "PRE.3.c",
   "PRE.3.d",
   "PRE.3.e",
   "PRE.4.a",
   "PRE.4.b",
   "PRE.4.c",
   "PRE.4.d",
   "PRE.4.e",
   "PRE.5.a",
   "PRE.5.b",
   "PRE.5.c",
   "PRE.5.d",
   "PRE.5.e",
   "PRE.5.f",
   "PRE.5.g",
   "PRE.6.c",
   "PRE.6.d",
   "PRE.7.b"
  ]
 },
 "care": {
  "label": "Staff interview — care of patients",
  "codes": [
   "AAC.12.c",
   "AAC.12.d",
   "COP.5.a",
   "COP.5.b",
   "COP.5.c",
   "COP.5.d",
   "COP.5.e",
   "COP.5.f",
   "COP.8.c",
   "COP.9.b",
   "COP.12.c",
   "COP.12.d",
   "COP.15.c",
   "COP.15.d",
   "COP.16.b",
   "COP.17.a",
   "COP.17.b",
   "COP.17.c",
   "COP.17.d",
   "COP.20.e",
   "MOM.3.d",
   "MOM.3.e",
   "MOM.3.f",
   "MOM.3.g",
   "MOM.7.a",
   "MOM.7.b",
   "MOM.7.c",
   "MOM.7.d",
   "MOM.7.e",
   "MOM.7.f",
   "MOM.7.g",
   "MOM.7.h",
   "MOM.8.d",
   "PRE.1.d",
   "IPC.1.c",
   "IPC.1.d",
   "PSQ.1.a",
   "PSQ.1.b",
   "PSQ.1.c",
   "PSQ.1.d",
   "PSQ.1.e",
   "PSQ.1.f",
   "PSQ.1.g"
  ]
 },
 "hr": {
  "label": "Staff interview — HR",
  "codes": [
   "HRM.3.a",
   "HRM.3.b",
   "HRM.3.c",
   "HRM.3.d",
   "HRM.3.e",
   "HRM.7.a",
   "HRM.7.b",
   "HRM.7.c",
   "HRM.7.d",
   "HRM.7.e",
   "HRM.9.a",
   "HRM.9.b",
   "HRM.9.c",
   "HRM.9.d"
  ]
 },
 "safety": {
  "label": "Staff interview — safety",
  "codes": [
   "AAC.8.d",
   "AAC.8.e",
   "AAC.11.e",
   "COP.4.a",
   "COP.4.b",
   "COP.4.c",
   "COP.4.d",
   "COP.11.f",
   "MOM.9.a",
   "MOM.9.b",
   "MOM.9.c",
   "MOM.9.d",
   "MOM.9.e",
   "IPC.4.d",
   "FMS.3.e",
   "FMS.7.c",
   "HRM.4.b",
   "HRM.4.c",
   "HRM.4.d",
   "HRM.6.a",
   "HRM.6.b",
   "HRM.6.c",
   "HRM.6.d",
   "HRM.6.e",
   "HRM.6.f",
   "HRM.6.g"
  ]
 }
};
