/* AQcredix — Quote of the Day.
   Three independent pools. The displayed quote is chosen by day-of-year, so every visitor
   sees the same quote on the same date and it changes once per day in all three languages.
   Pool sizes are deliberately not multiples of 365, so the cycle drifts year to year.
   Each entry: { t: quote text, a: attribution }
   Short quotable lines only — themes are health, medicine, patient care, patient safety,
   compassion, service and self-worth. */

window.QUOTE_DATA = {

  en: { label: "English", dir: "ltr", quotes: [
    { t: "Cure sometimes, treat often, comfort always.", a: "Attributed to Hippocrates" },
    { t: "Wherever the art of medicine is loved, there is also a love of humanity.", a: "Hippocrates" },
    { t: "First, do no harm.", a: "Principle of medical ethics" },
    { t: "The good physician treats the disease; the great physician treats the patient.", a: "William Osler" },
    { t: "Listen to your patient, he is telling you the diagnosis.", a: "William Osler" },
    { t: "Medicine is a science of uncertainty and an art of probability.", a: "William Osler" },
    { t: "The best preparation for tomorrow is doing your best today.", a: "H. Jackson Brown Jr." },
    { t: "To do nothing is also a good remedy.", a: "Hippocrates" },
    { t: "Let food be thy medicine and medicine be thy food.", a: "Attributed to Hippocrates" },
    { t: "Healing is a matter of time, but it is sometimes also a matter of opportunity.", a: "Hippocrates" },
    { t: "The greatest wealth is health.", a: "Virgil" },
    { t: "It is far more important to know what person the disease has than what disease the person has.", a: "Hippocrates" },
    { t: "Apparent failure may hold in its rough shell the germs of a success.", a: "Florence Nightingale" },
    { t: "I attribute my success to this: I never gave or took any excuse.", a: "Florence Nightingale" },
    { t: "The very first requirement in a hospital is that it should do the sick no harm.", a: "Florence Nightingale" },
    { t: "How very little can be done under the spirit of fear.", a: "Florence Nightingale" },
    { t: "Let us never consider ourselves finished nurses. We must be learning all of our lives.", a: "Florence Nightingale" },
    { t: "Nursing is an art, and if it is to be made an art, it requires exclusive devotion.", a: "Florence Nightingale" },
    { t: "Live your beliefs and you can turn the world around.", a: "Henry David Thoreau" },
    { t: "The art of medicine consists of amusing the patient while nature cures the disease.", a: "Voltaire" },
    { t: "He who has health has hope, and he who has hope has everything.", a: "Arabian proverb" },
    { t: "Take care of your body. It is the only place you have to live.", a: "Jim Rohn" },
    { t: "The patient is the most important member of the care team.", a: "Patient safety maxim" },
    { t: "Every system is perfectly designed to get the results it gets.", a: "Paul Batalden" },
    { t: "To err is human; to cover up is unforgivable; to fail to learn is inexcusable.", a: "Liam Donaldson" },
    { t: "Safety is not the absence of accidents, but the presence of defences.", a: "James Reason" },
    { t: "We cannot change the human condition, but we can change the conditions under which humans work.", a: "James Reason" },
    { t: "Quality is never an accident; it is always the result of intelligent effort.", a: "John Ruskin" },
    { t: "Without data, you are just another person with an opinion.", a: "W. Edwards Deming" },
    { t: "A bad system will beat a good person every time.", a: "W. Edwards Deming" },
    { t: "Every system is a product of its design; if you want a better result, redesign it.", a: "Quality improvement principle" },
    { t: "Improvement usually means doing something we have never done before.", a: "Shigeo Shingo" },
    { t: "Not everything that can be counted counts, and not everything that counts can be counted.", a: "William Bruce Cameron" },
    { t: "The secret of the care of the patient is in caring for the patient.", a: "Francis Weld Peabody" },
    { t: "Hospitals should be places of healing, not of harm.", a: "Patient safety principle" },
    { t: "Wash your hands. It remains the single most effective thing you can do.", a: "Infection control maxim" },
    { t: "Ignaz Semmelweis was right, and it cost him everything to say so.", a: "On the history of hand hygiene" },
    { t: "The physician should look upon the patient as a besieged city.", a: "Paracelsus" },
    { t: "Medicine cures diseases, but only physicians can cure patients.", a: "Carl Jung" },
    { t: "Compassion is not a relationship between the healer and the wounded.", a: "Pema Chödrön" },
    { t: "No one cares how much you know, until they know how much you care.", a: "Theodore Roosevelt" },
    { t: "Kindness is a language which the deaf can hear and the blind can see.", a: "Attributed to Mark Twain" },
    { t: "We rise by lifting others.", a: "Robert Ingersoll" },
    { t: "Service to others is the rent you pay for your room here on earth.", a: "Muhammad Ali" },
    { t: "The best way to find yourself is to lose yourself in the service of others.", a: "Mahatma Gandhi" },
    { t: "Everybody can be great, because everybody can serve.", a: "Martin Luther King Jr." },
    { t: "Be kind, for everyone you meet is fighting a hard battle.", a: "Attributed to Ian Maclaren" },
    { t: "You yourself, as much as anybody, deserve your love and affection.", a: "Attributed to the Buddha" },
    { t: "Almost everything will work again if you unplug it for a few minutes, including you.", a: "Anne Lamott" },
    { t: "Rest is not idleness.", a: "John Lubbock" },
    { t: "You cannot pour from an empty cup.", a: "Proverb on caregiver wellbeing" },
    { t: "Caring for myself is not self-indulgence, it is self-preservation.", a: "Audre Lorde" },
    { t: "Nobody can go back and start a new beginning, but anyone can start today.", a: "Maria Robinson" },
    { t: "There is no medicine like hope.", a: "Orison Swett Marden" },
    { t: "Hope is the thing with feathers that perches in the soul.", a: "Emily Dickinson" },
    { t: "The wound is the place where the light enters you.", a: "Rumi" },
    { t: "What we do for ourselves dies with us; what we do for others remains.", a: "Albert Pike" },
    { t: "It is health that is real wealth, and not pieces of gold and silver.", a: "Mahatma Gandhi" },
    { t: "The doctor of the future will give no medicine, but will interest patients in the care of the human frame.", a: "Attributed to Thomas Edison" },
    { t: "Prevention is better than cure.", a: "Desiderius Erasmus" },
    { t: "A healthy outside starts from the inside.", a: "Robert Urich" },
    { t: "Time and health are two precious assets we do not recognise until they are depleted.", a: "Denis Waitley" },
    { t: "The greatest medicine of all is to teach people how not to need it.", a: "Attributed to Hippocrates" },
    { t: "Patients do not care how much you know until they know you are listening.", a: "Clinical communication maxim" },
    { t: "Silence is one of the great arts of conversation.", a: "Marcus Tullius Cicero" },
    { t: "The most important thing in communication is hearing what is not said.", a: "Peter Drucker" },
    { t: "Excellence is not an act but a habit.", a: "Attributed to Aristotle" },
    { t: "Quality means doing it right when no one is looking.", a: "Henry Ford" },
    { t: "If you cannot describe what you are doing as a process, you do not know what you are doing.", a: "W. Edwards Deming" },
    { t: "Documentation is the memory of care.", a: "Medical records principle" },
    { t: "In the middle of difficulty lies opportunity.", a: "Albert Einstein" },
    { t: "The only real mistake is the one from which we learn nothing.", a: "Henry Ford" },
    { t: "An error does not become a mistake until you refuse to correct it.", a: "Orlando A. Battista" },
    { t: "Culture eats strategy for breakfast.", a: "Attributed to Peter Drucker" },
    { t: "Speak up. A question asked is safer than a doubt swallowed.", a: "Patient safety principle" },
    { t: "The strength of the team is each member; the strength of each member is the team.", a: "Phil Jackson" },
    { t: "Alone we can do so little; together we can do so much.", a: "Helen Keller" },
    { t: "Courage is what it takes to stand up and speak, and to sit down and listen.", a: "Winston Churchill" },
    { t: "Health is not valued till sickness comes.", a: "Thomas Fuller" },
    { t: "There is nothing noble in being superior to your fellow man.", a: "Ernest Hemingway" },
    { t: "The purpose of life is not to be happy, but to matter.", a: "Leo Rosten" },
    { t: "Do small things with great love.", a: "Attributed to Mother Teresa" },
    { t: "If you cannot feed a hundred people, then feed just one.", a: "Attributed to Mother Teresa" },
    { t: "Peace begins with a smile.", a: "Attributed to Mother Teresa" },
    { t: "Not all of us can do great things, but we can do small things with great love.", a: "Attributed to Mother Teresa" },
    { t: "Life's most persistent question is: what are you doing for others?", a: "Martin Luther King Jr." },
    { t: "Knowledge is of no value unless you put it into practice.", a: "Anton Chekhov" },
    { t: "The best doctor gives the least medicines.", a: "Benjamin Franklin" },
    { t: "Health is a state of complete physical, mental and social wellbeing.", a: "WHO Constitution, 1946" },
    { t: "Of all forms of inequality, injustice in health care is the most shocking.", a: "Martin Luther King Jr." },
    { t: "Sleep is the best meditation.", a: "The 14th Dalai Lama" }
  ]},

  ta: { label: "தமிழ்", dir: "ltr", quotes: [
    { t: "நோய் நாடி நோய் முதல் நாடி அது தணிக்கும் வாய் நாடி வாய்ப்பச் செயல்.", a: "திருக்குறள் 948 — திருவள்ளுவர்" },
    { t: "மருந்தென வேண்டாவாம் யாக்கைக்கு அருந்தியது அற்றது போற்றி உணின்.", a: "திருக்குறள் 942 — திருவள்ளுவர்" },
    { t: "அற்றால் அறவறிந்து உண்க அஃதுடம்பு பெற்றான் நெடிதுய்க்கும் ஆறு.", a: "திருக்குறள் 943 — திருவள்ளுவர்" },
    { t: "உற்றவன் தீர்ப்பான் மருந்துழைச் செல்வானென்று அப்பால் நாற்கூற்றே மருந்து.", a: "திருக்குறள் 950 — திருவள்ளுவர்" },
    { t: "மிகினும் குறையினும் நோய்செய்யும் நூலோர் வளிமுதலா எண்ணிய மூன்று.", a: "திருக்குறள் 941 — திருவள்ளுவர்" },
    { t: "இழிவறிந்து உண்பான்கண் இன்பம்போல் நிற்கும் கழிபேர் இரையான்கண் நோய்.", a: "திருக்குறள் 946 — திருவள்ளுவர்" },
    { t: "தீயள வன்றித் தெரியான் பெரிதுண்ணின் நோயள வின்றிப் படும்.", a: "திருக்குறள் 947 — திருவள்ளுவர்" },
    { t: "மருந்தே ஆயினும் விருந்தோடு உண்.", a: "பழமொழி" },
    { t: "அன்பின் வழியது உயிர்நிலை.", a: "திருக்குறள் 80 — திருவள்ளுவர்" },
    { t: "அறவினை யாதெனில் கொல்லாமை.", a: "திருக்குறள் 321 — திருவள்ளுவர்" },
    { t: "பிறர்க்கின்னா முற்பகல் செய்யின் தமக்கின்னா பிற்பகல் தாமே வரும்.", a: "திருக்குறள் 319 — திருவள்ளுவர்" },
    { t: "தன்னுயிர் தான்அறப் பெற்றானை ஏனைய மன்னுயி ரெல்லாந் தொழும்.", a: "திருக்குறள் 268 — திருவள்ளுவர்" },
    { t: "யாதனின் யாதனின் நீங்கியான் நோதல் அதனின் அதனின் இலன்.", a: "திருக்குறள் 341 — திருவள்ளுவர்" },
    { t: "செய்யற்க செய்யக் கெடும்.", a: "திருக்குறள் 466 — திருவள்ளுவர்" },
    { t: "எண்ணித் துணிக கருமம்.", a: "திருக்குறள் 467 — திருவள்ளுவர்" },
    { t: "தெரிந்த இனத்தொடு தேர்ந்தெண்ணிச் செய்வார்க்கு அரும்பொருள் யாதொன்றும் இல்.", a: "திருக்குறள் 462 — திருவள்ளுவர்" },
    { t: "நன்றாற்ற லுள்ளுந் தவறுண்டு அவரவர் பண்பறிந் தாற்றாக் கடை.", a: "திருக்குறள் 469 — திருவள்ளுவர்" },
    { t: "ஊக்கம் உடைமை ஆக்கத்திற்கு அழகு.", a: "கொன்றைவேந்தன் — ஔவையார்" },
    { t: "அன்பே சிவம்.", a: "திருமூலர், திருமந்திரம்" },
    { t: "ஒன்றே குலம் ஒருவனே தேவன்.", a: "திருமூலர், திருமந்திரம்" },
    { t: "உடம்பார் அழியில் உயிரார் அழிவர்.", a: "திருமூலர், திருமந்திரம்" },
    { t: "உடம்பை வளர்த்தேன் உயிர்வளர்த் தேனே.", a: "திருமூலர், திருமந்திரம்" },
    { t: "யாதும் ஊரே யாவரும் கேளிர்.", a: "புறநானூறு 192 — கணியன் பூங்குன்றனார்" },
    { t: "தீதும் நன்றும் பிறர்தர வாரா.", a: "புறநானூறு 192 — கணியன் பூங்குன்றனார்" },
    { t: "நோதலும் தணிதலும் அவற்றோ ரன்ன.", a: "புறநானூறு 192 — கணியன் பூங்குன்றனார்" },
    { t: "உண்டி கொடுத்தோர் உயிர் கொடுத்தோரே.", a: "மணிமேகலை — சீத்தலைச் சாத்தனார்" },
    { t: "பசி என்னும் பாவியை அறுத்தல் அறம்.", a: "மணிமேகலை நெறி" },
    { t: "நல்லது செய்தல் ஆற்றீ ராயினும் அல்லது செய்தல் ஓம்புமின்.", a: "நாலடியார்" },
    { t: "இன்னா செய்தார்க்கும் இனியவே செய்யாக்கால் என்ன பயத்ததோ சால்பு.", a: "திருக்குறள் 987 — திருவள்ளுவர்" },
    { t: "பிறர்நோய் தன்நோய் போல் போற்றாக் கடை.", a: "திருக்குறள் நெறி" },
    { t: "மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்.", a: "திருக்குறள் 34 — திருவள்ளுவர்" },
    { t: "அழுக்காறு அவாவெகுளி இன்னாச்சொல் நான்கும் இழுக்கா இயன்றது அறம்.", a: "திருக்குறள் 35 — திருவள்ளுவர்" },
    { t: "செய்க பொருளை.", a: "திருக்குறள் 759 — திருவள்ளுவர்" },
    { t: "கற்க கசடறக் கற்பவை கற்றபின் நிற்க அதற்குத் தக.", a: "திருக்குறள் 391 — திருவள்ளுவர்" },
    { t: "தொட்டனைத் தூறும் மணற்கேணி மாந்தர்க்குக் கற்றனைத் தூறும் அறிவு.", a: "திருக்குறள் 396 — திருவள்ளுவர்" },
    { t: "கேடில் விழுச்செல்வம் கல்வி.", a: "திருக்குறள் 400 — திருவள்ளுவர்" },
    { t: "எப்பொருள் யார்யார்வாய்க் கேட்பினும் அப்பொருள் மெய்ப்பொருள் காண்பது அறிவு.", a: "திருக்குறள் 423 — திருவள்ளுவர்" },
    { t: "எண்ணென்ப ஏனை எழுத்தென்ப இவ்விரண்டும் கண்ணென்ப வாழும் உயிர்க்கு.", a: "திருக்குறள் 392 — திருவள்ளுவர்" },
    { t: "அறிவினான் ஆகுவ துண்டோ பிறிதின்நோய் தன்நோய்போல் போற்றாக் கடை.", a: "திருக்குறள் 315 — திருவள்ளுவர்" },
    { t: "வையகம் பாலிக்கும் வண்மை.", a: "பாரதியார்" },
    { t: "நோயற்ற வாழ்வே குறைவற்ற செல்வம்.", a: "பழமொழி" },
    { t: "சுத்தம் சோறு போடும்.", a: "பழமொழி" },
    { t: "மருந்தும் விருந்தும் மூன்று நாள்.", a: "பழமொழி" },
    { t: "அளவுக்கு மிஞ்சினால் அமிர்தமும் நஞ்சு.", a: "பழமொழி" },
    { t: "ஆடு நனைகிறதென்று ஓநாய் அழுததாம்.", a: "பழமொழி" },
    { t: "காலம் தவறினால் கை நழுவும்.", a: "பழமொழி" },
    { t: "முற்காப்பு நல்ல மருந்து.", a: "பழமொழி" },
    { t: "உடல் நலம் இருந்தால் உலகம் நமது.", a: "பழமொழி" },
    { t: "தூங்குவது மருந்து, விழிப்பது வேலை.", a: "பழமொழி" },
    { t: "நிற்க அதற்குத் தக — கற்றது கைப்பொருள்.", a: "திருக்குறள் நெறி" },
    { t: "அகர முதல எழுத்தெல்லாம்.", a: "திருக்குறள் 1 — திருவள்ளுவர்" },
    { t: "வெள்ளத் தனைய மலர்நீட்டம்.", a: "திருக்குறள் 595 — திருவள்ளுவர்" },
    { t: "ஊழையும் உப்பக்கம் காண்பர் உலைவின்றித் தாழாது உஞற்று பவர்.", a: "திருக்குறள் 620 — திருவள்ளுவர்" },
    { t: "இடுக்கண் வருங்கால் நகுக.", a: "திருக்குறள் 621 — திருவள்ளுவர்" },
    { t: "அரியகற்று ஆசற்றார் கண்ணும் தெரியுங்கால் இன்மை அரிதே வெளிறு.", a: "திருக்குறள் 503 — திருவள்ளுவர்" },
    { t: "தெரிந்து தெளிந்து செயல்.", a: "திருக்குறள் நெறி" },
    { t: "மனமது செம்மையானால் மந்திரம் செபிக்க வேண்டா.", a: "தாயுமானவர்" },
    { t: "உள்ளம் உருகினால் உடல் உருகும்.", a: "சித்தர் பாடல்" },
    { t: "தன்னை அறிதல் தலையாய அறிவு.", a: "சித்தர் நெறி" },
    { t: "பிறருக்கு உதவும் கை பெருமை உடையது.", a: "பழமொழி" }
  ]},

  hi: { label: "हिन्दी", dir: "ltr", quotes: [
    { t: "पहला सुख निरोगी काया।", a: "हिन्दी लोकोक्ति" },
    { t: "सेवा परमो धर्मः।", a: "संस्कृत सूक्ति" },
    { t: "सर्वे भवन्तु सुखिनः, सर्वे सन्तु निरामयाः।", a: "बृहदारण्यक उपनिषद्" },
    { t: "अहिंसा परमो धर्मः।", a: "महाभारत" },
    { t: "शरीरमाद्यं खलु धर्मसाधनम्।", a: "कालिदास, कुमारसम्भव" },
    { t: "स्वस्थस्य स्वास्थ्य रक्षणम्, आतुरस्य विकार प्रशमनम्।", a: "चरक संहिता" },
    { t: "जो स्वस्थ है उसका स्वास्थ्य बनाए रखना भी चिकित्सा है।", a: "आयुर्वेद का मूल सिद्धांत" },
    { t: "हितभुक्, मितभुक्, ऋतभुक्।", a: "आयुर्वेदिक सूत्र" },
    { t: "वैद्य को रोगी में अपना ही स्वरूप देखना चाहिए।", a: "चरक संहिता का भाव" },
    { t: "जीवन का उद्देश्य दूसरों की सेवा करना है।", a: "महात्मा गांधी" },
    { t: "स्वास्थ्य ही असली धन है, सोना-चाँदी नहीं।", a: "महात्मा गांधी" },
    { t: "स्वयं को खोजने का सबसे अच्छा तरीका है दूसरों की सेवा में स्वयं को खो देना।", a: "महात्मा गांधी" },
    { t: "उठो, जागो और तब तक मत रुको जब तक लक्ष्य प्राप्त न हो जाए।", a: "स्वामी विवेकानंद" },
    { t: "जो दूसरों के लिए जीता है, वही सचमुच जीता है।", a: "स्वामी विवेकानंद" },
    { t: "दरिद्र नारायण की सेवा ही सच्ची पूजा है।", a: "स्वामी विवेकानंद" },
    { t: "शक्ति जीवन है, निर्बलता मृत्यु है।", a: "स्वामी विवेकानंद" },
    { t: "जीव पर दया करना ही शिव की सेवा है।", a: "स्वामी विवेकानंद" },
    { t: "मन के हारे हार है, मन के जीते जीत।", a: "हिन्दी लोकोक्ति" },
    { t: "करत करत अभ्यास के जड़मति होत सुजान।", a: "वृंद" },
    { t: "रहिमन देखि बड़ेन को, लघु न दीजिए डारि।", a: "रहीम" },
    { t: "जहाँ काम आवे सुई, कहा करे तरवारि।", a: "रहीम" },
    { t: "ऐसी बानी बोलिए, मन का आपा खोय। औरन को सीतल करै, आपहु सीतल होय।", a: "कबीर" },
    { t: "बड़ा हुआ तो क्या हुआ, जैसे पेड़ खजूर।", a: "कबीर" },
    { t: "पोथी पढ़ि पढ़ि जग मुआ, पंडित भया न कोय।", a: "कबीर" },
    { t: "दुख में सुमिरन सब करे, सुख में करे न कोय।", a: "कबीर" },
    { t: "जिन खोजा तिन पाइयाँ, गहरे पानी पैठ।", a: "कबीर" },
    { t: "धीरे-धीरे रे मना, धीरे सब कुछ होय।", a: "कबीर" },
    { t: "साईं इतना दीजिए, जा में कुटुम समाय।", a: "कबीर" },
    { t: "निंदक नियरे राखिए, आँगन कुटी छवाय।", a: "कबीर" },
    { t: "बुरा जो देखन मैं चला, बुरा न मिलिया कोय।", a: "कबीर" },
    { t: "परहित सरिस धर्म नहिं भाई।", a: "तुलसीदास, रामचरितमानस" },
    { t: "दया धर्म का मूल है।", a: "तुलसीदास" },
    { t: "क्षमा बड़न को चाहिए, छोटन को उतपात।", a: "तुलसीदास" },
    { t: "प्रभु दयालु सब पर समभावा।", a: "तुलसीदास, रामचरितमानस" },
    { t: "सुख-दुख सम करि जानिए।", a: "भगवद्गीता का भाव" },
    { t: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।", a: "भगवद्गीता 2.47" },
    { t: "योगः कर्मसु कौशलम्।", a: "भगवद्गीता 2.50" },
    { t: "युक्ताहारविहारस्य योगो भवति दुःखहा।", a: "भगवद्गीता 6.17" },
    { t: "आत्मा को न शस्त्र काट सकते हैं, न आग जला सकती है।", a: "भगवद्गीता 2.23" },
    { t: "मनुष्य स्वयं अपना मित्र है और स्वयं अपना शत्रु।", a: "भगवद्गीता 6.5" },
    { t: "सत्यमेव जयते।", a: "मुण्डक उपनिषद्" },
    { t: "वसुधैव कुटुम्बकम्।", a: "महा उपनिषद्" },
    { t: "मातृदेवो भव, पितृदेवो भव, आचार्यदेवो भव।", a: "तैत्तिरीय उपनिषद्" },
    { t: "तमसो मा ज्योतिर्गमय।", a: "बृहदारण्यक उपनिषद्" },
    { t: "विद्या ददाति विनयम्।", a: "हितोपदेश" },
    { t: "उद्यमेन हि सिध्यन्ति कार्याणि न मनोरथैः।", a: "हितोपदेश" },
    { t: "परोपकाराय सतां विभूतयः।", a: "सुभाषितम्" },
    { t: "परोपकाराय फलन्ति वृक्षाः।", a: "सुभाषितम्" },
    { t: "अति सर्वत्र वर्जयेत्।", a: "सुभाषितम्" },
    { t: "क्षणशः कणशश्चैव विद्यामर्थं च साधयेत्।", a: "चाणक्य नीति" },
    { t: "आरोग्यं परमं भाग्यं, स्वास्थ्यं सर्वार्थसाधनम्।", a: "सुभाषितम्" },
    { t: "जान है तो जहान है।", a: "हिन्दी लोकोक्ति" },
    { t: "इलाज से बेहतर बचाव है।", a: "हिन्दी लोकोक्ति" },
    { t: "स्वच्छता ही सेवा है।", a: "हिन्दी सूक्ति" },
    { t: "जैसा अन्न, वैसा मन।", a: "हिन्दी लोकोक्ति" },
    { t: "समय पर एक टाँका, नौ टाँकों की बचत।", a: "लोकोक्ति" },
    { t: "जल ही जीवन है।", a: "हिन्दी सूक्ति" },
    { t: "हँसना सबसे सस्ती दवा है।", a: "हिन्दी सूक्ति" },
    { t: "नींद से बढ़कर कोई औषधि नहीं।", a: "हिन्दी सूक्ति" },
    { t: "जो अपना ध्यान नहीं रख सकता, वह औरों का क्या रखेगा।", a: "हिन्दी सूक्ति" },
    { t: "गलती करना मानवीय है, उसे छिपाना अक्षम्य।", a: "रोगी सुरक्षा का सिद्धांत" },
    { t: "सवाल पूछना संदेह पालने से सुरक्षित है।", a: "रोगी सुरक्षा का सिद्धांत" },
    { t: "हाथ धोना आज भी सबसे प्रभावी उपाय है।", a: "संक्रमण नियंत्रण सूत्र" }
  ]}
};
