/* AQcredix — the forms, checklists and registers library.
 *
 * Source: the hospital's own working inventory of what each department maintains for
 * NABH — real items across checklists, forms/consents and registers, tagged to the
 * department that owns each one. Field lists are written from general clinical
 * documentation practice — what such a record must capture to be usable and auditable —
 * not transcribed from any NABH publication. `detailed:true` entries have a full field
 * list and a download; the rest use a generic template for their category until someone
 * writes the specific one, the same reviewed/unreviewed pattern as nabh-summary.js.
 */
window.DOC_LIBRARY = [
  {
    id: "checklist-fire-exitinguisher",
    name: "Fire Exitinguisher",
    category: "checklist",
    department: "Quality Department",
    detailed: true,
    why: "Monthly verification that every extinguisher is in date, charged, and where it should be — an assessor checks the tag, not the policy.",
    fields: [
      "Location / floor",
      "Extinguisher ID",
      "Type (CO2, ABC, Water, Foam)",
      "Expiry / next refill date",
      "Pressure gauge in green zone (Y/N)",
      "Pin and seal intact (Y/N)",
      "Signage visible and unobstructed (Y/N)",
      "Access unobstructed (Y/N)",
      "Checked by",
      "Date and time",
      "Corrective action if any item fails",
    ],
    analytics: "Extinguishers overdue for refill, failed checks by location, trend over the last 6 rounds."
  },
  {
    id: "checklist-billing-floor-passage-02",
    name: "Billing/Floor/Passage 02",
    category: "checklist",
    department: "Facilities",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-lift-checklist-03",
    name: "Lift checklist 03",
    category: "checklist",
    department: "Facilities",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-material-gate-pass",
    name: "Material Gate Pass",
    category: "checklist",
    department: "Security",
    detailed: true,
    why: "Tracks material leaving the building for service, loan or disposal. Security's primary accountability document, and the one most often lost track of on paper.",
    fields: [
      "Gate pass number (sequential, never reused)",
      "Date and time",
      "Department",
      "Particulars — item, make, model, serial/asset code",
      "Reason / purpose",
      "Type: returnable or non-returnable",
      "Quantity sent",
      "Expected date of return (returnable only)",
      "Mode of transport / vehicle number",
      "Prepared by (name, signature, date)",
      "Department in-charge (name, signature)",
      "Taken by (name, signature)",
      "Security check — outward (name, signature, time)",
      "Return: date returned, quantity returned, received by, security check — inward",
    ],
    analytics: "Live in AQcredix: passes currently out, days overdue, issued this month, by department."
  },
  {
    id: "checklist-ventilator-associated-events",
    name: "Ventilator Associated Events",
    category: "checklist",
    department: "Infection Control",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-central-line-associated-blood-stream-infection",
    name: "Central Line Associated Blood stream Infection",
    category: "checklist",
    department: "Infection Control",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-surgical-site-infection",
    name: "Surgical site infection",
    category: "checklist",
    department: "Infection Control",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-catheter-associated-urinary-tract-infection",
    name: "Catheter Associated Urinary Tract Infection",
    category: "checklist",
    department: "Infection Control",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-hand-hygiene-observation",
    name: "Hand Hygiene - Observation",
    category: "checklist",
    department: "Infection Control",
    detailed: true,
    why: "Direct observation of the five moments — the compliance rate an assessor asks for and the one that is easiest to overstate without a real record.",
    fields: [
      "Unit / ward observed",
      "Observer",
      "Date and time",
      "Moment 1: before touching a patient (compliant Y/N)",
      "Moment 2: before a clean/aseptic procedure",
      "Moment 3: after body fluid exposure risk",
      "Moment 4: after touching a patient",
      "Moment 5: after touching patient surroundings",
      "Staff category observed (doctor/nurse/support)",
      "Compliance % for the round",
    ],
    analytics: "Rolling compliance % by unit and staff category, trended against your target — this is exactly what the Rounds engine already scores."
  },
  {
    id: "checklist-infection-control-daily-checklists",
    name: "Infection Control Daily Checklists",
    category: "checklist",
    department: "Infection Control",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-bio-medical-waste-segregation-audit",
    name: "Bio medical Waste segregation Audit",
    category: "checklist",
    department: "Facilities",
    detailed: true,
    why: "Confirms colour-coded segregation is actually happening at the point of generation, not only at the collection point.",
    fields: [
      "Area audited",
      "Date",
      "Yellow bag — correct waste only (Y/N)",
      "Red bag — correct waste only (Y/N)",
      "White/puncture-proof — sharps only (Y/N)",
      "Blue bag — glass/metal only (Y/N)",
      "Bags labelled with barcode (Y/N)",
      "Weighing register updated (Y/N)",
      "Deviations noted",
      "Auditor",
    ],
    analytics: "Segregation error rate by area and waste category, month on month."
  },
  {
    id: "checklist-bundle-care-tracking-checklist",
    name: "Bundle Care Tracking Checklist",
    category: "checklist",
    department: "Infection Control",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-radiology-handing-over-checklist",
    name: "Radiology Handing Over Checklist",
    category: "checklist",
    department: "Radiology",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-ventilator",
    name: "Ventilator",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-defibrillator",
    name: "Defibrillator",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-syringe-pump",
    name: "Syringe Pump",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-infusion-pump",
    name: "Infusion Pump",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-cardiac-monitoring",
    name: "Cardiac Monitoring",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-ecg-machine",
    name: "ECG Machine",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-anaesthesia",
    name: "Anaesthesia",
    category: "checklist",
    department: "Quality Department",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-portable-suction-machine",
    name: "Portable suction machine",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-wall-mounted-oxygen-flow-meter",
    name: "Wall mounted oxygen flow meter",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-wall-mounted-suction",
    name: "Wall Mounted Suction",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-b-type-oxygen-cylinder",
    name: "B type Oxygen cylinder",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-fridge-temperature",
    name: "Fridge Temperature",
    category: "checklist",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "checklist-new-born-checklist",
    name: "New Born checklist",
    category: "checklist",
    department: "Neonatology / NICU",
    detailed: false,
    fields: [
      "Area / unit checked",
      "Date and time",
      "Items verified against the checklist (list each)",
      "Pass / fail / observation for each item",
      "Checked by (name, signature)",
      "Corrective action if any item fails",
      "Frequency this checklist runs on",
    ],
    analytics: null
  },
  {
    id: "form-high-risk-explicit-consent",
    name: "High Risk Explicit Consent",
    category: "form",
    subtype: "Consent",
    department: "Operation Theatre",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-dialyzer-reuse-consent",
    name: "Dialyzer Reuse Consent",
    category: "form",
    subtype: "Consent",
    department: "Dialysis / Nephrology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-chemo-consent",
    name: "Chemo consent",
    category: "form",
    subtype: "Consent",
    department: "Oncology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-artificial-insemination-husband-semen",
    name: "Artificial Insemination Husband semen",
    category: "form",
    subtype: "Consent",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-artificial-insemination-donor-semen",
    name: "Artificial Insemination Donor semen",
    category: "form",
    subtype: "Consent",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-consent-for-eolc",
    name: "Consent for EOLC",
    category: "form",
    subtype: "Consent",
    department: "Medical / Clinical",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-patient-condition-counselling-form",
    name: "Patient Condition counselling Form",
    category: "form",
    subtype: "Consent",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-consent-for-procedure",
    name: "Consent for Procedure",
    category: "form",
    subtype: "Consent",
    department: "Medical / Clinical",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-mtp",
    name: "MTP",
    category: "form",
    subtype: "Consent",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-family-planning",
    name: "Family Planning",
    category: "form",
    subtype: "Consent",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-mri-ct-x-ray-consent",
    name: "MRI CT X RAY Consent",
    category: "form",
    subtype: "Consent",
    department: "Medical / Clinical",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-anaestia-consent",
    name: "Anaestia consent",
    category: "form",
    subtype: "Consent",
    department: "Anaesthesia",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-high-risk-procedure-consent",
    name: "High risk Procedure Consent",
    category: "form",
    subtype: "Consent",
    department: "Operation Theatre",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-surgical-consent",
    name: "Surgical Consent",
    category: "form",
    subtype: "Consent",
    department: "Operation Theatre",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-day-care-consent",
    name: "Day care consent",
    category: "form",
    subtype: "Consent",
    department: "Operation Theatre",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-paediatric-consent",
    name: "Paediatric Consent",
    category: "form",
    subtype: "Consent",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-og-consent",
    name: "OG Consent",
    category: "form",
    subtype: "Consent",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-blood-request-form",
    name: "Blood Request Form",
    category: "form",
    subtype: "Form",
    department: "Blood Bank",
    detailed: true,
    why: "The record a blood bank cross-matches against and an assessor traces from request to transfusion.",
    fields: [
      "Patient name, UHID, age, sex",
      "Ward / bed",
      "Blood group and Rh",
      "Component requested (whole blood/PRBC/FFP/platelets)",
      "Units required",
      "Indication for transfusion",
      "Relevant history (prior transfusion reactions)",
      "Requesting consultant (name, signature)",
      "Date and time of request",
      "Sample collected by",
      "Cross-match result",
      "Issued by / received by",
    ],
    analytics: "Requests by blood group and component, turnaround time from request to issue."
  },
  {
    id: "form-nurisng-initial-assesment",
    name: "Nurisng initial Assesment",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-doctors-initial-assessment",
    name: "Doctors initial Assessment",
    category: "form",
    subtype: "Form",
    department: "Medical / Clinical",
    detailed: true,
    why: "The first clinical entry an assessor checks a medical record against — completeness here is a proxy for the whole record.",
    fields: [
      "Patient UHID, name, age, sex",
      "Date and time of assessment",
      "Chief complaint and history of presenting illness",
      "Past medical/surgical history",
      "Allergies",
      "Examination findings (systemic)",
      "Provisional diagnosis",
      "Investigations ordered",
      "Treatment plan",
      "Assessing doctor (name, signature, time)",
    ],
    analytics: "Completion rate within the required time window, by department and by doctor."
  },
  {
    id: "form-blood-issue-form",
    name: "Blood Issue Form",
    category: "form",
    subtype: "Form",
    department: "Blood Bank",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-nursing-assessment-chart",
    name: "Nursing Assessment Chart",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-patient-family-education-record",
    name: "Patient & Family Education Record",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-investigation-chart",
    name: "Investigation Chart",
    category: "form",
    subtype: "Form",
    department: "Medical / Clinical",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-intake-output-chart",
    name: "Intake & Output chart",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-blood-transfusion-monitoring-chart",
    name: "Blood Transfusion Monitoring Chart",
    category: "form",
    subtype: "Form",
    department: "Blood Bank",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-national-early-warning-score-clinical-chart",
    name: "National Early Warning Score – Clinical Chart",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-in-patient-billing-chart",
    name: "In Patient Billing Chart",
    category: "form",
    subtype: "Form",
    department: "Billing / Front Office",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-clinical-procedure-monitoring-chart",
    name: "Clinical Procedure Monitoring chart",
    category: "form",
    subtype: "Form",
    department: "Medical / Clinical",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-doctors-progress-notes",
    name: "Doctors progress Notes",
    category: "form",
    subtype: "Form",
    department: "Medical / Clinical",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-anaesthesia-consent",
    name: "Anaesthesia Consent",
    category: "form",
    subtype: "Form",
    department: "Quality Department",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-cause-of-death",
    name: "Cause of death",
    category: "form",
    subtype: "Form",
    department: "Medical Records",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-antibiotic-chart",
    name: "Antibiotic Chart",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-drug-chart",
    name: "Drug Chart",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-mortality",
    name: "Mortality",
    category: "form",
    subtype: "Form",
    department: "Medical Records",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-chemo-record-part",
    name: "Chemo Record Part",
    category: "form",
    subtype: "Form",
    department: "Oncology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-chemo-restrain-monitoring",
    name: "Chemo Restrain Monitoring",
    category: "form",
    subtype: "Form",
    department: "Oncology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-neonatal-data-form",
    name: "Neonatal DATA Form",
    category: "form",
    subtype: "Form",
    department: "Neonatology / NICU",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-adime",
    name: "ADIME",
    category: "form",
    subtype: "Form",
    department: "Dietetics",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-eternal-chart",
    name: "Eternal Chart",
    category: "form",
    subtype: "Form",
    department: "Neonatology / NICU",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-nutrition-progress",
    name: "Nutrition Progress",
    category: "form",
    subtype: "Form",
    department: "Dietetics",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-nutritional-assessment-for-paediatrics",
    name: "Nutritional Assessment for Paediatrics",
    category: "form",
    subtype: "Form",
    department: "Dietetics",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-nutritional-assessment-for-antenatal-postnatal",
    name: "Nutritional Assessment for antenatal & Postnatal",
    category: "form",
    subtype: "Form",
    department: "Dietetics",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-financial-counselling-form-on-admission",
    name: "Financial counselling form on admission",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-financial-counselling-form-icu-admission",
    name: "Financial counselling form ICU admission",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-dengue-monitoring-chart",
    name: "Dengue Monitoring Chart",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-braden-scale",
    name: "Braden scale",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-pain-assessment-form",
    name: "Pain Assessment Form",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-early-warning-score",
    name: "Early warning score",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-humpty-dumpty-scale",
    name: "Humpty Dumpty Scale",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-partograph-chart",
    name: "Partograph chart",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-breast-feeding-assessment",
    name: "Breast Feeding assessment",
    category: "form",
    subtype: "Form",
    department: "Nursing",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-prenatal-assessment",
    name: "Prenatal Assessment",
    category: "form",
    subtype: "Form",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-mgso4-monitorng",
    name: "Mgso4 Monitorng",
    category: "form",
    subtype: "Form",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-birth-detail-form",
    name: "Birth Detail Form",
    category: "form",
    subtype: "Form",
    department: "Obstetrics & Gynaecology",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-death-detail-form",
    name: "Death Detail form",
    category: "form",
    subtype: "Form",
    department: "Medical Records",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-brought-dead-form",
    name: "Brought Dead form",
    category: "form",
    subtype: "Form",
    department: "Medical Records",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-narcotic-form",
    name: "Narcotic Form",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: true,
    why: "The controlled-drug register a pharmacy must reconcile to zero discrepancy — one of the first things a pharmacy inspection checks.",
    fields: [
      "Drug name, strength, batch number",
      "Opening balance",
      "Date, patient UHID, prescriber, quantity issued",
      "Running balance",
      "Issued by (signature)",
      "Witnessed by (signature, for Schedule X drugs)",
      "Closing balance / physical count",
      "Discrepancy noted and explained",
    ],
    analytics: "Discrepancy count per reconciliation, drugs nearing reorder level."
  },
  {
    id: "form-medication",
    name: "Medication",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-reconciliation-form",
    name: "reconciliation form",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-high-end-antibiotic-justification-form",
    name: "High end Antibiotic Justification Form",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-new-drug-requestion-form",
    name: "New Drug Requestion Form",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "form-icra-picra-form",
    name: "ICRA PICRA Form",
    category: "form",
    subtype: "Form",
    department: "Pharmacy",
    detailed: false,
    fields: [
      "Patient UHID, name, age, sex (where clinical)",
      "Date and time",
      "The specific clinical or administrative content this form exists to capture",
      "Completed by (name, signature, designation)",
      "Countersigned / verified by, where required",
    ],
    analytics: null
  },
  {
    id: "register-ambulance-ems-case-sheet",
    name: "Ambulance – EMS Case Sheet",
    category: "register",
    department: "Emergency Department",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-x-ray-nominal-register",
    name: "X- ray Nominal Register",
    category: "register",
    department: "Radiology",
    detailed: true,
    why: "The log linking every film taken to a named patient and a reporting radiologist — traced during a radiology safety review.",
    fields: [
      "Serial number (date-wise)",
      "Date and time",
      "Patient UHID and name",
      "Referring doctor",
      "Examination performed",
      "Technologist",
      "Radiologist reporting",
      "Report despatch date",
      "Remarks",
    ],
    analytics: "Volume by examination type, average report turnaround time."
  },
  {
    id: "register-ct-nominal-register",
    name: "CT Nominal Register",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-mri-nominal-register",
    name: "MRI Nominal Register",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-dexa-scan-nominal-register",
    name: "Dexa Scan Nominal Register",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-mammogram-nominal-register",
    name: "Mammogram Nominal Register",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-opg-nominal-register",
    name: "OPG Nominal Register",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-cath-lab-nominal-register",
    name: "Cath Lab Nominal Register",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-cath-lab-bill-book-ptca",
    name: "Cath Lab Bill book PTCA",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-cath-lab-bill-book-angio",
    name: "Cath Lab Bill book Angio",
    category: "register",
    department: "Radiology",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-work-permit",
    name: "Work Permit",
    category: "register",
    department: "Biomedical",
    detailed: true,
    why: "Authorises hot work, confined-space entry or electrical work inside the hospital — the record that shows a contractor was cleared before starting.",
    fields: [
      "Permit number and date",
      "Area / equipment",
      "Type of work (hot work, confined space, electrical, height)",
      "Contractor / agency and workers named",
      "Hazards identified and controls in place",
      "Isolation confirmed (LOTO) where applicable",
      "Issued by (safety officer)",
      "Time started / time closed",
      "Area handed back clear (Y/N)",
    ],
    analytics: "Permits by type and area, any closed with an incident noted against them."
  },
  {
    id: "register-sample-receiving-sheets",
    name: "Sample Receiving sheets",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-receiving-issuing",
    name: "Receiving & Issuing",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-loading-unloading",
    name: "Loading & unloading",
    category: "register",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-consumable-register",
    name: "Consumable Register",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-recall",
    name: "Recall",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-surgical-instruments-washing",
    name: "Surgical Instruments Washing",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-breakdown",
    name: "Breakdown",
    category: "register",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-surgical-instruments-inventory",
    name: "Surgical instruments Inventory",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-planned-preventive-maintenance",
    name: "Planned Preventive Maintenance",
    category: "register",
    department: "Biomedical",
    detailed: true,
    why: "The PM log biomedical maintains alongside the AQcredix register — many hospitals still keep both until they trust the digital one.",
    fields: [
      "Equipment name and asset code",
      "Location / department",
      "PM frequency",
      "Scheduled date",
      "Date performed",
      "Checklist items verified",
      "Result (pass/fail/observation)",
      "Engineer / vendor",
      "Next due date",
      "Downtime, if any",
    ],
    analytics: "This maps directly onto the AQcredix equipment register and calibration cycles — one record, not two."
  },
  {
    id: "register-cylinder-stock-register",
    name: "Cylinder stock Register",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-reading-sheet",
    name: "Reading Sheet",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-nominal-reister",
    name: "Nominal Reister",
    category: "register",
    department: "Medical Records",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-gate-pass",
    name: "Gate pass",
    category: "register",
    department: "Biomedical",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
  {
    id: "register-outside-body",
    name: "Outside Body",
    category: "register",
    department: "Central Sterile Supply Department (CSSD)",
    detailed: false,
    fields: [
      "Serial number",
      "Date",
      "Patient / item identifier",
      "Details specific to this register",
      "Recorded by",
      "Cross-reference to the source form or event",
      "Remarks",
    ],
    analytics: null
  },
];